// Code generated by make generate; DO NOT EDIT.
//go:generate go-enum --names --nocase --values

package enums

// ENUM(
//
//	common/in_recovery
//	common/query_stats_available
//	common/query_stats_enabled
//	common/query_stats_readable
//	common/server_version
//	common/server_version_full
//	common/server_version_num
//	common/summary
//	connections/connection_sources
//	connections/connection_states
//	connections/stat_activity
//	constraints/invalid_constraints
//	database/pgss_stats_reset_time
//	database/size
//	database/stats_reset_time
//	fks/possible_nulls
//	fks/possible_similar1
//	fks/possible_similar2
//	fks/type_mismatch
//	indexes/all_scans
//	indexes/bloat
//	indexes/btree_on_array
//	indexes/caching
//	indexes/duplicate
//	indexes/hit_rate
//	indexes/invalid_or_not_ready
//	indexes/missing
//	indexes/similar_1
//	indexes/similar_2
//	indexes/similar_3
//	indexes/top_k_by_size
//	indexes/unused
//	indexes/usage
//	maintenance/autovacuum_freeze_max_age
//	maintenance/info
//	maintenance/transaction_id_danger
//	maintenance/vacuum_progress
//	progress/analyze
//	progress/base_backup
//	progress/cluster
//	progress/index
//	progress/vacuum
//	queries/blocked
//	queries/report
//	queries/running
//	queries/top_10_by_time
//	queries/top_10_by_wal
//	replication/lag
//	replication/slots
//	settings/analyze_settings
//	settings/autovacuum_settings
//	settings/pg_settings
//	tables/caching
//	tables/hit_rate
//	tables/partitions
//	tables/top_k_by_size
//	)
type Query string
