// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enums

import (
	"fmt"
	"strings"
)

const (
	// QueryCommonDatabaseUsers is a Query of type common/database_users.
	QueryCommonDatabaseUsers Query = "common/database_users"
	// QueryCommonInRecovery is a Query of type common/in_recovery.
	QueryCommonInRecovery Query = "common/in_recovery"
	// QueryCommonQueryStatsAvailable is a Query of type common/query_stats_available.
	QueryCommonQueryStatsAvailable Query = "common/query_stats_available"
	// QueryCommonQueryStatsEnabled is a Query of type common/query_stats_enabled.
	QueryCommonQueryStatsEnabled Query = "common/query_stats_enabled"
	// QueryCommonQueryStatsReadable is a Query of type common/query_stats_readable.
	QueryCommonQueryStatsReadable Query = "common/query_stats_readable"
	// QueryCommonServerVersion is a Query of type common/server_version.
	QueryCommonServerVersion Query = "common/server_version"
	// QueryCommonServerVersionFull is a Query of type common/server_version_full.
	QueryCommonServerVersionFull Query = "common/server_version_full"
	// QueryCommonServerVersionNum is a Query of type common/server_version_num.
	QueryCommonServerVersionNum Query = "common/server_version_num"
	// QueryCommonSummary is a Query of type common/summary.
	QueryCommonSummary Query = "common/summary"
	// QueryConnectionsConnectionSources is a Query of type connections/connection_sources.
	QueryConnectionsConnectionSources Query = "connections/connection_sources"
	// QueryConnectionsConnectionStates is a Query of type connections/connection_states.
	QueryConnectionsConnectionStates Query = "connections/connection_states"
	// QueryConnectionsStatActivity is a Query of type connections/stat_activity.
	QueryConnectionsStatActivity Query = "connections/stat_activity"
	// QueryConstraintsInvalidConstraints is a Query of type constraints/invalid_constraints.
	QueryConstraintsInvalidConstraints Query = "constraints/invalid_constraints"
	// QueryDatabasePgssStatsResetTime is a Query of type database/pgss_stats_reset_time.
	QueryDatabasePgssStatsResetTime Query = "database/pgss_stats_reset_time"
	// QueryDatabaseSize is a Query of type database/size.
	QueryDatabaseSize Query = "database/size"
	// QueryDatabaseStatsResetTime is a Query of type database/stats_reset_time.
	QueryDatabaseStatsResetTime Query = "database/stats_reset_time"
	// QueryFksPossibleNulls is a Query of type fks/possible_nulls.
	QueryFksPossibleNulls Query = "fks/possible_nulls"
	// QueryFksPossibleSimilar1 is a Query of type fks/possible_similar1.
	QueryFksPossibleSimilar1 Query = "fks/possible_similar1"
	// QueryFksPossibleSimilar2 is a Query of type fks/possible_similar2.
	QueryFksPossibleSimilar2 Query = "fks/possible_similar2"
	// QueryFksTypeMismatch is a Query of type fks/type_mismatch.
	QueryFksTypeMismatch Query = "fks/type_mismatch"
	// QueryIndexesAllScans is a Query of type indexes/all_scans.
	QueryIndexesAllScans Query = "indexes/all_scans"
	// QueryIndexesBloat is a Query of type indexes/bloat.
	QueryIndexesBloat Query = "indexes/bloat"
	// QueryIndexesBtreeOnArray is a Query of type indexes/btree_on_array.
	QueryIndexesBtreeOnArray Query = "indexes/btree_on_array"
	// QueryIndexesCaching is a Query of type indexes/caching.
	QueryIndexesCaching Query = "indexes/caching"
	// QueryIndexesDuplicate is a Query of type indexes/duplicate.
	QueryIndexesDuplicate Query = "indexes/duplicate"
	// QueryIndexesHitRate is a Query of type indexes/hit_rate.
	QueryIndexesHitRate Query = "indexes/hit_rate"
	// QueryIndexesInvalidOrNotReady is a Query of type indexes/invalid_or_not_ready.
	QueryIndexesInvalidOrNotReady Query = "indexes/invalid_or_not_ready"
	// QueryIndexesMissing is a Query of type indexes/missing.
	QueryIndexesMissing Query = "indexes/missing"
	// QueryIndexesSimilar1 is a Query of type indexes/similar_1.
	QueryIndexesSimilar1 Query = "indexes/similar_1"
	// QueryIndexesSimilar2 is a Query of type indexes/similar_2.
	QueryIndexesSimilar2 Query = "indexes/similar_2"
	// QueryIndexesSimilar3 is a Query of type indexes/similar_3.
	QueryIndexesSimilar3 Query = "indexes/similar_3"
	// QueryIndexesTopKBySize is a Query of type indexes/top_k_by_size.
	QueryIndexesTopKBySize Query = "indexes/top_k_by_size"
	// QueryIndexesUnused is a Query of type indexes/unused.
	QueryIndexesUnused Query = "indexes/unused"
	// QueryIndexesUsage is a Query of type indexes/usage.
	QueryIndexesUsage Query = "indexes/usage"
	// QueryMaintenanceAutovacuumFreezeMaxAge is a Query of type maintenance/autovacuum_freeze_max_age.
	QueryMaintenanceAutovacuumFreezeMaxAge Query = "maintenance/autovacuum_freeze_max_age"
	// QueryMaintenanceInfo is a Query of type maintenance/info.
	QueryMaintenanceInfo Query = "maintenance/info"
	// QueryMaintenanceTransactionIdDanger is a Query of type maintenance/transaction_id_danger.
	QueryMaintenanceTransactionIdDanger Query = "maintenance/transaction_id_danger"
	// QueryMaintenanceVacuumProgress is a Query of type maintenance/vacuum_progress.
	QueryMaintenanceVacuumProgress Query = "maintenance/vacuum_progress"
	// QueryProgressAnalyze is a Query of type progress/analyze.
	QueryProgressAnalyze Query = "progress/analyze"
	// QueryProgressBaseBackup is a Query of type progress/base_backup.
	QueryProgressBaseBackup Query = "progress/base_backup"
	// QueryProgressCluster is a Query of type progress/cluster.
	QueryProgressCluster Query = "progress/cluster"
	// QueryProgressIndex is a Query of type progress/index.
	QueryProgressIndex Query = "progress/index"
	// QueryProgressVacuum is a Query of type progress/vacuum.
	QueryProgressVacuum Query = "progress/vacuum"
	// QueryQueriesBlocked is a Query of type queries/blocked.
	QueryQueriesBlocked Query = "queries/blocked"
	// QueryQueriesReport is a Query of type queries/report.
	QueryQueriesReport Query = "queries/report"
	// QueryQueriesRunning is a Query of type queries/running.
	QueryQueriesRunning Query = "queries/running"
	// QueryQueriesTop10ByTime is a Query of type queries/top_10_by_time.
	QueryQueriesTop10ByTime Query = "queries/top_10_by_time"
	// QueryQueriesTop10ByWal is a Query of type queries/top_10_by_wal.
	QueryQueriesTop10ByWal Query = "queries/top_10_by_wal"
	// QueryReplicationLag is a Query of type replication/lag.
	QueryReplicationLag Query = "replication/lag"
	// QueryReplicationSlots is a Query of type replication/slots.
	QueryReplicationSlots Query = "replication/slots"
	// QuerySettingsAnalyzeSettings is a Query of type settings/analyze_settings.
	QuerySettingsAnalyzeSettings Query = "settings/analyze_settings"
	// QuerySettingsAutovacuumSettings is a Query of type settings/autovacuum_settings.
	QuerySettingsAutovacuumSettings Query = "settings/autovacuum_settings"
	// QuerySettingsPgSettings is a Query of type settings/pg_settings.
	QuerySettingsPgSettings Query = "settings/pg_settings"
	// QueryTablesCaching is a Query of type tables/caching.
	QueryTablesCaching Query = "tables/caching"
	// QueryTablesDescribeCheckConstraints is a Query of type tables/describe_check_constraints.
	QueryTablesDescribeCheckConstraints Query = "tables/describe_check_constraints"
	// QueryTablesDescribeColumns is a Query of type tables/describe_columns.
	QueryTablesDescribeColumns Query = "tables/describe_columns"
	// QueryTablesDescribeFkConstraints is a Query of type tables/describe_fk_constraints.
	QueryTablesDescribeFkConstraints Query = "tables/describe_fk_constraints"
	// QueryTablesDescribeIndexes is a Query of type tables/describe_indexes.
	QueryTablesDescribeIndexes Query = "tables/describe_indexes"
	// QueryTablesDescribeMetadata is a Query of type tables/describe_metadata.
	QueryTablesDescribeMetadata Query = "tables/describe_metadata"
	// QueryTablesDescribeReferencedBy is a Query of type tables/describe_referenced_by.
	QueryTablesDescribeReferencedBy Query = "tables/describe_referenced_by"
	// QueryTablesHitRate is a Query of type tables/hit_rate.
	QueryTablesHitRate Query = "tables/hit_rate"
	// QueryTablesPartitions is a Query of type tables/partitions.
	QueryTablesPartitions Query = "tables/partitions"
	// QueryTablesTopKBySize is a Query of type tables/top_k_by_size.
	QueryTablesTopKBySize Query = "tables/top_k_by_size"
)

var ErrInvalidQuery = fmt.Errorf("not a valid Query, try [%s]", strings.Join(_QueryNames, ", "))

var _QueryNames = []string{
	string(QueryCommonDatabaseUsers),
	string(QueryCommonInRecovery),
	string(QueryCommonQueryStatsAvailable),
	string(QueryCommonQueryStatsEnabled),
	string(QueryCommonQueryStatsReadable),
	string(QueryCommonServerVersion),
	string(QueryCommonServerVersionFull),
	string(QueryCommonServerVersionNum),
	string(QueryCommonSummary),
	string(QueryConnectionsConnectionSources),
	string(QueryConnectionsConnectionStates),
	string(QueryConnectionsStatActivity),
	string(QueryConstraintsInvalidConstraints),
	string(QueryDatabasePgssStatsResetTime),
	string(QueryDatabaseSize),
	string(QueryDatabaseStatsResetTime),
	string(QueryFksPossibleNulls),
	string(QueryFksPossibleSimilar1),
	string(QueryFksPossibleSimilar2),
	string(QueryFksTypeMismatch),
	string(QueryIndexesAllScans),
	string(QueryIndexesBloat),
	string(QueryIndexesBtreeOnArray),
	string(QueryIndexesCaching),
	string(QueryIndexesDuplicate),
	string(QueryIndexesHitRate),
	string(QueryIndexesInvalidOrNotReady),
	string(QueryIndexesMissing),
	string(QueryIndexesSimilar1),
	string(QueryIndexesSimilar2),
	string(QueryIndexesSimilar3),
	string(QueryIndexesTopKBySize),
	string(QueryIndexesUnused),
	string(QueryIndexesUsage),
	string(QueryMaintenanceAutovacuumFreezeMaxAge),
	string(QueryMaintenanceInfo),
	string(QueryMaintenanceTransactionIdDanger),
	string(QueryMaintenanceVacuumProgress),
	string(QueryProgressAnalyze),
	string(QueryProgressBaseBackup),
	string(QueryProgressCluster),
	string(QueryProgressIndex),
	string(QueryProgressVacuum),
	string(QueryQueriesBlocked),
	string(QueryQueriesReport),
	string(QueryQueriesRunning),
	string(QueryQueriesTop10ByTime),
	string(QueryQueriesTop10ByWal),
	string(QueryReplicationLag),
	string(QueryReplicationSlots),
	string(QuerySettingsAnalyzeSettings),
	string(QuerySettingsAutovacuumSettings),
	string(QuerySettingsPgSettings),
	string(QueryTablesCaching),
	string(QueryTablesDescribeCheckConstraints),
	string(QueryTablesDescribeColumns),
	string(QueryTablesDescribeFkConstraints),
	string(QueryTablesDescribeIndexes),
	string(QueryTablesDescribeMetadata),
	string(QueryTablesDescribeReferencedBy),
	string(QueryTablesHitRate),
	string(QueryTablesPartitions),
	string(QueryTablesTopKBySize),
}

// QueryNames returns a list of possible string values of Query.
func QueryNames() []string {
	tmp := make([]string, len(_QueryNames))
	copy(tmp, _QueryNames)
	return tmp
}

// QueryValues returns a list of the values for Query
func QueryValues() []Query {
	return []Query{
		QueryCommonDatabaseUsers,
		QueryCommonInRecovery,
		QueryCommonQueryStatsAvailable,
		QueryCommonQueryStatsEnabled,
		QueryCommonQueryStatsReadable,
		QueryCommonServerVersion,
		QueryCommonServerVersionFull,
		QueryCommonServerVersionNum,
		QueryCommonSummary,
		QueryConnectionsConnectionSources,
		QueryConnectionsConnectionStates,
		QueryConnectionsStatActivity,
		QueryConstraintsInvalidConstraints,
		QueryDatabasePgssStatsResetTime,
		QueryDatabaseSize,
		QueryDatabaseStatsResetTime,
		QueryFksPossibleNulls,
		QueryFksPossibleSimilar1,
		QueryFksPossibleSimilar2,
		QueryFksTypeMismatch,
		QueryIndexesAllScans,
		QueryIndexesBloat,
		QueryIndexesBtreeOnArray,
		QueryIndexesCaching,
		QueryIndexesDuplicate,
		QueryIndexesHitRate,
		QueryIndexesInvalidOrNotReady,
		QueryIndexesMissing,
		QueryIndexesSimilar1,
		QueryIndexesSimilar2,
		QueryIndexesSimilar3,
		QueryIndexesTopKBySize,
		QueryIndexesUnused,
		QueryIndexesUsage,
		QueryMaintenanceAutovacuumFreezeMaxAge,
		QueryMaintenanceInfo,
		QueryMaintenanceTransactionIdDanger,
		QueryMaintenanceVacuumProgress,
		QueryProgressAnalyze,
		QueryProgressBaseBackup,
		QueryProgressCluster,
		QueryProgressIndex,
		QueryProgressVacuum,
		QueryQueriesBlocked,
		QueryQueriesReport,
		QueryQueriesRunning,
		QueryQueriesTop10ByTime,
		QueryQueriesTop10ByWal,
		QueryReplicationLag,
		QueryReplicationSlots,
		QuerySettingsAnalyzeSettings,
		QuerySettingsAutovacuumSettings,
		QuerySettingsPgSettings,
		QueryTablesCaching,
		QueryTablesDescribeCheckConstraints,
		QueryTablesDescribeColumns,
		QueryTablesDescribeFkConstraints,
		QueryTablesDescribeIndexes,
		QueryTablesDescribeMetadata,
		QueryTablesDescribeReferencedBy,
		QueryTablesHitRate,
		QueryTablesPartitions,
		QueryTablesTopKBySize,
	}
}

// String implements the Stringer interface.
func (x Query) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Query) IsValid() bool {
	_, err := ParseQuery(string(x))
	return err == nil
}

var _QueryValue = map[string]Query{
	"common/database_users":                 QueryCommonDatabaseUsers,
	"common/in_recovery":                    QueryCommonInRecovery,
	"common/query_stats_available":          QueryCommonQueryStatsAvailable,
	"common/query_stats_enabled":            QueryCommonQueryStatsEnabled,
	"common/query_stats_readable":           QueryCommonQueryStatsReadable,
	"common/server_version":                 QueryCommonServerVersion,
	"common/server_version_full":            QueryCommonServerVersionFull,
	"common/server_version_num":             QueryCommonServerVersionNum,
	"common/summary":                        QueryCommonSummary,
	"connections/connection_sources":        QueryConnectionsConnectionSources,
	"connections/connection_states":         QueryConnectionsConnectionStates,
	"connections/stat_activity":             QueryConnectionsStatActivity,
	"constraints/invalid_constraints":       QueryConstraintsInvalidConstraints,
	"database/pgss_stats_reset_time":        QueryDatabasePgssStatsResetTime,
	"database/size":                         QueryDatabaseSize,
	"database/stats_reset_time":             QueryDatabaseStatsResetTime,
	"fks/possible_nulls":                    QueryFksPossibleNulls,
	"fks/possible_similar1":                 QueryFksPossibleSimilar1,
	"fks/possible_similar2":                 QueryFksPossibleSimilar2,
	"fks/type_mismatch":                     QueryFksTypeMismatch,
	"indexes/all_scans":                     QueryIndexesAllScans,
	"indexes/bloat":                         QueryIndexesBloat,
	"indexes/btree_on_array":                QueryIndexesBtreeOnArray,
	"indexes/caching":                       QueryIndexesCaching,
	"indexes/duplicate":                     QueryIndexesDuplicate,
	"indexes/hit_rate":                      QueryIndexesHitRate,
	"indexes/invalid_or_not_ready":          QueryIndexesInvalidOrNotReady,
	"indexes/missing":                       QueryIndexesMissing,
	"indexes/similar_1":                     QueryIndexesSimilar1,
	"indexes/similar_2":                     QueryIndexesSimilar2,
	"indexes/similar_3":                     QueryIndexesSimilar3,
	"indexes/top_k_by_size":                 QueryIndexesTopKBySize,
	"indexes/unused":                        QueryIndexesUnused,
	"indexes/usage":                         QueryIndexesUsage,
	"maintenance/autovacuum_freeze_max_age": QueryMaintenanceAutovacuumFreezeMaxAge,
	"maintenance/info":                      QueryMaintenanceInfo,
	"maintenance/transaction_id_danger":     QueryMaintenanceTransactionIdDanger,
	"maintenance/vacuum_progress":           QueryMaintenanceVacuumProgress,
	"progress/analyze":                      QueryProgressAnalyze,
	"progress/base_backup":                  QueryProgressBaseBackup,
	"progress/cluster":                      QueryProgressCluster,
	"progress/index":                        QueryProgressIndex,
	"progress/vacuum":                       QueryProgressVacuum,
	"queries/blocked":                       QueryQueriesBlocked,
	"queries/report":                        QueryQueriesReport,
	"queries/running":                       QueryQueriesRunning,
	"queries/top_10_by_time":                QueryQueriesTop10ByTime,
	"queries/top_10_by_wal":                 QueryQueriesTop10ByWal,
	"replication/lag":                       QueryReplicationLag,
	"replication/slots":                     QueryReplicationSlots,
	"settings/analyze_settings":             QuerySettingsAnalyzeSettings,
	"settings/autovacuum_settings":          QuerySettingsAutovacuumSettings,
	"settings/pg_settings":                  QuerySettingsPgSettings,
	"tables/caching":                        QueryTablesCaching,
	"tables/describe_check_constraints":     QueryTablesDescribeCheckConstraints,
	"tables/describe_columns":               QueryTablesDescribeColumns,
	"tables/describe_fk_constraints":        QueryTablesDescribeFkConstraints,
	"tables/describe_indexes":               QueryTablesDescribeIndexes,
	"tables/describe_metadata":              QueryTablesDescribeMetadata,
	"tables/describe_referenced_by":         QueryTablesDescribeReferencedBy,
	"tables/hit_rate":                       QueryTablesHitRate,
	"tables/partitions":                     QueryTablesPartitions,
	"tables/top_k_by_size":                  QueryTablesTopKBySize,
}

// ParseQuery attempts to convert a string to a Query.
func ParseQuery(name string) (Query, error) {
	if x, ok := _QueryValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _QueryValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Query(""), fmt.Errorf("%s is %w", name, ErrInvalidQuery)
}
