/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ActivitySpikeTrigger {
  Enabled: boolean
  /** Moving-average baseline window, Go duration string (e.g. "30m") */
  WindowSize: string
  ActiveThresholdPct: number
  /** How long activity must stay above the threshold, Go duration string (e.g. "2m"). Must be <= WindowSize / 2, otherwise the spike inflates its own baseline before it can fire. Single dips shorter than half this value are tolerated, provided 70% of the probes stay above the threshold. */
  SpikeDuration: string
  /** Snapshot the aftermath once activity stays below threshold this long; "0s" disables */
  RecoveryDuration: string
  /** Scheduled follow-up snapshot this long after a spike (persisted queue); "0s" disables */
  DeferredInterval: string
}
