/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ActivitySpikeTrigger {
  Enabled: boolean
  /** Go duration string (e.g. "5m") */
  WindowSize: string
  ActiveThresholdPct: number
  /** Go duration string (e.g. "5m") */
  SpikeDuration: string
  /** Snapshot the aftermath once activity stays below threshold this long; "0s" disables */
  RecoveryDuration: string
  /** Scheduled follow-up snapshot this long after a spike (persisted queue); "0s" disables */
  DeferredInterval: string
}
