/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type AdminPersonalAccessTokenRole =
  (typeof AdminPersonalAccessTokenRole)[keyof typeof AdminPersonalAccessTokenRole]

export const AdminPersonalAccessTokenRole = {
  viewer: 'viewer',
  admin: 'admin',
} as const
