/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPersonalAccessTokenRole } from './adminPersonalAccessTokenRole'

/**
 * A personal access token as shown to an administrator — the owner's view plus the owning principal.
 */
export interface AdminPersonalAccessToken {
  id: string
  name: string
  /** The principal (OIDC email) that owns the token. */
  owner: string
  /** Token prefix shown for identification (not the secret). */
  prefix: string
  role: AdminPersonalAccessTokenRole
  created_at: string
  /** @nullable */
  last_used_at?: string | null
  /** @nullable */
  expires_at?: string | null
  /**
   * When the token was revoked; null for a live token. Only ever set when include_revoked was requested.
   * @nullable
   */
  revoked_at?: string | null
}
