/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type AdminUserRole = (typeof AdminUserRole)[keyof typeof AdminUserRole]

export const AdminUserRole = {
  viewer: 'viewer',
  admin: 'admin',
} as const
