/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUserRole } from './adminUserRole'

/**
 * A principal that has signed in at least once. Roles are shown as last seen from the identity provider; they are not editable here.
 */
export interface AdminUser {
  /** The principal (OIDC email); the same key a token's owner field carries. */
  subject: string
  name: string
  role: AdminUserRole
  /** When the principal first signed in. */
  created_at: string
  /** @nullable */
  last_login_at?: string | null
  /** Number of the principal's personal access tokens that are not revoked. */
  tokens: number
}
