/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { AuthInfoMode } from './authInfoMode'
import type { AuthInfoPatMinRole } from './authInfoPatMinRole'

export interface AuthInfo {
  mode: AuthInfoMode
  oidc_login_url?: string
  enable_query_stats_reset?: boolean
  /** True when personal access tokens can be minted (snapshot storage is configured). */
  pat_enabled?: boolean
  /** Minimum role allowed to manage personal access tokens (auth.pat_min_role); the client combines it with the signed-in user's role. */
  pat_min_role?: AuthInfoPatMinRole
}
