/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Minimum role allowed to manage personal access tokens (auth.pat_min_role); the client combines it with the signed-in user's role.
 */
export type AuthInfoPatMinRole = (typeof AuthInfoPatMinRole)[keyof typeof AuthInfoPatMinRole]

export const AuthInfoPatMinRole = {
  admin: 'admin',
  viewer: 'viewer',
} as const
