/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type AuthInfoMode = (typeof AuthInfoMode)[keyof typeof AuthInfoMode]

export const AuthInfoMode = {
  none: 'none',
  token: 'token',
  oidc: 'oidc',
} as const
