/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ActivitySpikeTrigger } from './activitySpikeTrigger'
import type { RoleChangeTrigger } from './roleChangeTrigger'

export interface AutoSnapshotTriggerDefaults {
  ActivitySpike: ActivitySpikeTrigger
  RoleChange: RoleChangeTrigger
}
