/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { AutoSnapshotTriggerDefaults } from './autoSnapshotTriggerDefaults'

export interface AutoSnapshotConfig {
  Enabled: boolean
  /** Go duration string (e.g. "30s") */
  PollInterval: string
  /** Go duration string (e.g. "1h") */
  MaxSnapshotFrequency: string
  /** Total storage size target in bytes, 0 to disable */
  RetentionBytes: number
  RetentionMinDays: number
  MinBaselineActive: number
  Defaults: AutoSnapshotTriggerDefaults
}
