/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { AutoSnapshotLeaderInfo } from './autoSnapshotLeaderInfo'

export interface AutoSnapshotStatus {
  Available: boolean
  Enabled: boolean
  Leader?: AutoSnapshotLeaderInfo
}
