/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { AutoSnapshotClusterOverrideOverrides } from './autoSnapshotClusterOverrideOverrides'
import type { AutoSnapshotTriggerDefaults } from './autoSnapshotTriggerDefaults'

export interface AutoSnapshotClusterOverride {
  ClusterName: string
  /** Partial overrides (activity_spike / role_change subfields) */
  Overrides: AutoSnapshotClusterOverrideOverrides
  Effective: AutoSnapshotTriggerDefaults
}
