/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { AutoSnapshotTriggerDefaults } from './autoSnapshotTriggerDefaults'

export interface AutoSnapshotConfig {
  Enabled: boolean
  /** Go duration string (e.g. "30s") */
  PollInterval: string
  /** Go duration string (e.g. "1h") */
  MaxSnapshotFrequency: string
  /** Total storage size target in bytes, 0 to disable */
  RetentionBytes: number
  RetentionMinDays: number
  MinBaselineActive: number
  CaptureLocks: boolean
  LockProbeCount: number
  /** Go duration string between lock probes (e.g. "500ms") */
  LockProbeInterval: string
  /** Reset pg_stat_statements after each auto-snapshot (independent of the manual UI reset flag) */
  ResetQueryStats: boolean
  /** Capture hot-objects delta snapshots (tables/indexes activity tops) */
  HotEnabled: boolean
  /** Standard 5-field cron expression, UTC unless prefixed with CRON_TZ=<zone> (e.g. "0 3 * * *") */
  HotSchedule: string
  /** Exact top size stored per metric class; the tail is kept as a histogram */
  HotTopN: number
  /** Age-based retention of hot-objects snapshots, days */
  HotRetentionDays: number
  Defaults: AutoSnapshotTriggerDefaults
}
