/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { AutoSnapshotClusterOverrideInputOverrides } from './autoSnapshotClusterOverrideInputOverrides'

export interface AutoSnapshotClusterOverrideInput {
  /** Partial overrides (activity_spike / role_change subfields) */
  Overrides: AutoSnapshotClusterOverrideInputOverrides
}
