/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Partial overrides (activity_spike / role_change subfields)
 */
export type AutoSnapshotClusterOverrideInputOverrides = { [key: string]: unknown }
