/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterInstance } from './clusterInstance'

export interface Cluster {
  name?: string
  /** cluster origin, e.g. "static" or "yandex-mdb" */
  source?: string
  /** true when cluster logs can be searched via GET /api/logs */
  supports_logs?: boolean
  /** log streams the bound source serves, e.g. postgresql and pooler */
  log_streams?: string[]
  instances?: ClusterInstance[]
  databases?: string[]
}
