/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ClusterSnapshotSummary {
  ClusterName: string
  /** Total created snapshots (outcome = snapshot_created) */
  Snapshots: number
  /** Created snapshots via the activity_spike trigger */
  ActivitySpike: number
  /** Created snapshots via the role_change trigger */
  RoleChange: number
  /** Failed attempts (outcome = error) */
  Errors: number
}
