/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * severity values each stream accepts, keyed by stream name, in the casing the source stores them; the log search rejects any other value
 */
export type ClusterLogSeverities = { [key: string]: string[] }
