/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterInstance } from './clusterInstance'

export interface Cluster {
  name?: string
  instances?: ClusterInstance[]
  databases?: string[]
}
