/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ColdTablesStatusStatus } from './coldTablesStatusStatus'

export interface ColdTablesStatus {
  status: ColdTablesStatusStatus
  /** Days without writes after which a table counts as cold. */
  window_days: number
  /** Days of unbroken history on this instance; present when status is warming_up. */
  observed_days?: number
  /** Cold tables in the database; present when status is available. */
  count?: number
}
