/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type ColdTablesStatusStatus =
  (typeof ColdTablesStatusStatus)[keyof typeof ColdTablesStatusStatus]

export const ColdTablesStatusStatus = {
  available: 'available',
  no_storage: 'no_storage',
  disabled: 'disabled',
  stale: 'stale',
  warming_up: 'warming_up',
  standby: 'standby',
  error: 'error',
} as const
