/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface CommonSummary {
  Namespace: string
  Kind: string
  ApproxSize: string
  ApproxSizeBytes: number
  Amount: number
}
