/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ConnectionStatActivity {
  Pid: number
  Database: string
  UserName: string
  ApplicationName: string
  ClientAddr: string
  State: string
  Ssl: boolean
  BackendType: string
}
