/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ConnectionSource {
  Database: string
  Username: string
  ApplicationName: string
  ClientAddr: string
  TotalConnections: number
}
