/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Database whose pg_stat_statements view is read. The extension may be installed in one database only, and in a schema outside search_path; its contents are instance-wide either way. Defaults to any database of the instance that has the extension.

 */
export type DatabaseOptionalParameter = string
