/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface DatabaseHealth {
  Deadlocks: number
  Conflicts: number
  /** @nullable */
  ChecksumFailures?: number | null
  /** @nullable */
  ChecksumLastFailure?: string | null
  XactCommit: number
  XactRollback: number
  RollbackRatio: number
  /** @nullable */
  StatsReset?: string | null
}
