/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'

export type DeleteHealthScoreWeightsParams = {
  cluster_name: ClusterNameParameter
}
