/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface FksPossibleSimilar {
  Table: string;
  FkName: string;
  Fk1Name: string;
}
