/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface FkTypeMismatch {
  FkName: string
  FromRel: string
  RelAttNames: string[]
  ToRel: string
  ToRelAttNames: string[]
}
