/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetAutosnapshotTriggerEventsParams = {
  cluster_name?: string
  outcome?: string
  trigger_type?: string
  from?: string
  to?: string
  limit?: number
  offset?: number
}
