/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetHealthScoreFleetParams = {
  /**
   * Number of instances to return (default 20).
   * @minimum 1
   * @maximum 50
   */
  limit?: number
  /**
   * Clusters to include; empty means the whole fleet.
   */
  cluster_name?: string[]
  /**
   * Score every instance exactly, skipping the prefilter. Allowed only when health_score.fleet.allow_exhaustive is set.
   */
  exhaustive?: boolean
}
