/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { GetHotObjectHistoryKind } from './getHotObjectHistoryKind'

export type GetHotObjectHistoryParams = {
  cluster_name: ClusterNameParameter
  database: DatabaseParameter
  kind: GetHotObjectHistoryKind
  schema: string
  object: string
  /**
   * How many days back to look.
   */
  days?: number
}
