/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetHotObjectHistoryKind =
  (typeof GetHotObjectHistoryKind)[keyof typeof GetHotObjectHistoryKind]

export const GetHotObjectHistoryKind = {
  table: 'table',
  index: 'index',
} as const
