/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetHotPercentileClass =
  (typeof GetHotPercentileClass)[keyof typeof GetHotPercentileClass]

export const GetHotPercentileClass = {
  reads: 'reads',
  writes: 'writes',
  io: 'io',
} as const
