/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { GetHotPercentileClass } from './getHotPercentileClass'
import type { GetHotPercentileKind } from './getHotPercentileKind'

export type GetHotPercentileParams = {
  cluster_name: ClusterNameParameter
  database: DatabaseParameter
  kind: GetHotPercentileKind
  schema: string
  object: string
  class?: GetHotPercentileClass
}
