/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { InstanceParameter } from './instanceParameter'

export type GetHealthScoreRecommendationsParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  /**
 * When set, only rules applicable at the per-database level are
returned (Connections / Replication rules are filtered out).

 */
  database?: string
}
