/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { InstanceParameter } from './instanceParameter'

export type GetHealthScoreHistoryParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  from: string
  to: string
  /**
   * Sampling step in seconds (default 300).
   */
  step_seconds?: number
}
