/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetHotPercentileKind = (typeof GetHotPercentileKind)[keyof typeof GetHotPercentileKind]

export const GetHotPercentileKind = {
  table: 'table',
  index: 'index',
} as const
