/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { GetIOHistoryGroupBy } from './getIOHistoryGroupBy'
import type { InstanceParameter } from './instanceParameter'

export type GetIOHistoryParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  from: string
  to: string
  /**
   * Dimensions each series keeps; the rest are summed over.
   */
  group_by?: GetIOHistoryGroupBy
  /**
   * Maximum number of points per series; adjacent intervals are summed to fit.
   */
  points?: number
  /**
   * Keep only this pg_stat_io context (normal, vacuum, bulkread, bulkwrite, init).
   */
  context?: string
  /**
   * Keep only this backend type.
   */
  backend_type?: string
  /**
   * Keep only this object (relation, temp relation, wal).
   */
  object?: string
}
