/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetIndexesUnusedReportVerdict =
  (typeof GetIndexesUnusedReportVerdict)[keyof typeof GetIndexesUnusedReportVerdict]

export const GetIndexesUnusedReportVerdict = {
  drop_candidate: 'drop_candidate',
  used: 'used',
  stale_evidence: 'stale_evidence',
  insufficient_data: 'insufficient_data',
  unknown: 'unknown',
} as const
