/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetIndexesHotClass = (typeof GetIndexesHotClass)[keyof typeof GetIndexesHotClass]

export const GetIndexesHotClass = {
  reads: 'reads',
  io: 'io',
} as const
