/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { GetIndexesHotClass } from './getIndexesHotClass'

export type GetIndexesHotParams = {
  cluster_name: ClusterNameParameter
  database: DatabaseParameter
  class?: GetIndexesHotClass
  /**
   * Exact capture time of the snapshot to read (a value from snapshot.dates); defaults to the latest snapshot.
   */
  at?: string
  limit?: number
  offset?: number
}
