/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { InstanceParameter } from './instanceParameter'

export type GetIndexesCachingParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  database: DatabaseParameter
  limit?: number
  offset?: number
}
