/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'

export type GetIndexesUnusedReportParams = {
  cluster_name: ClusterNameParameter
  database: DatabaseParameter
  limit?: number
  offset?: number
}
