/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetIOHistoryGroupBy = (typeof GetIOHistoryGroupBy)[keyof typeof GetIOHistoryGroupBy]

export const GetIOHistoryGroupBy = {
  context: 'context',
  backend_type: 'backend_type',
  full: 'full',
} as const
