/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetLogsPlansCompareServiceType =
  (typeof GetLogsPlansCompareServiceType)[keyof typeof GetLogsPlansCompareServiceType]

export const GetLogsPlansCompareServiceType = {
  postgresql: 'postgresql',
  pooler: 'pooler',
} as const
