/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetLogsCheckServiceType =
  (typeof GetLogsCheckServiceType)[keyof typeof GetLogsCheckServiceType]

export const GetLogsCheckServiceType = {
  postgresql: 'postgresql',
  pooler: 'pooler',
} as const
