/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { GetLogsCheckServiceType } from './getLogsCheckServiceType'

export type GetLogsCheckParams = {
  cluster_name: ClusterNameParameter
  service_type: GetLogsCheckServiceType
}
