/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetLogsInsightsServiceType =
  (typeof GetLogsInsightsServiceType)[keyof typeof GetLogsInsightsServiceType]

export const GetLogsInsightsServiceType = {
  postgresql: 'postgresql',
  pooler: 'pooler',
} as const
