/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetLogsScanGroupsOrder =
  (typeof GetLogsScanGroupsOrder)[keyof typeof GetLogsScanGroupsOrder]

export const GetLogsScanGroupsOrder = {
  sum: 'sum',
  max: 'max',
  count: 'count',
} as const
