/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { GetLogsPlansCompareServiceType } from './getLogsPlansCompareServiceType'

export type GetLogsPlansCompareParams = {
  cluster_name: ClusterNameParameter
  service_type: GetLogsPlansCompareServiceType
  /**
   * start of the current window; required unless scan_id names a stored scan, and rejected together with it
   */
  from?: string
  /**
   * end of the current window
   */
  to?: string
  /**
   * a stored scan to take the current window from, instead of reading it again; its numbers are the ones that scan answered with
   */
  scan_id?: string
  baseline_from: string
  baseline_to: string
  host?: string
  /**
   * compare the plans of this statement only, as a string to preserve int64 precision in JavaScript
   */
  query_id?: string
  /**
   * statements the answer carries, worst first
   */
  limit?: number
}
