/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetLogsServiceType = (typeof GetLogsServiceType)[keyof typeof GetLogsServiceType]

export const GetLogsServiceType = {
  postgresql: 'postgresql',
  pooler: 'pooler',
} as const
