/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { GetLogsScanGroupsOrder } from './getLogsScanGroupsOrder'

export type GetLogsScanGroupsParams = {
  /**
   * keep the groups of this query_id only
   */
  query_id?: string
  /**
   * keep the groups whose plan tripped at least one rule
   */
  with_findings?: boolean
  order?: GetLogsScanGroupsOrder
  limit?: number
  offset?: number
}
