/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { GetLogsServiceType } from './getLogsServiceType'

export type GetLogsParams = {
  cluster_name: ClusterNameParameter
  service_type: GetLogsServiceType
  from: string
  to: string
  severity?: string[]
  host?: string
  /**
   * Substrings that must all be present in the message (case-insensitive, AND).
   */
  message?: string[]
  /**
   * Drop records whose message contains any of these substrings (case-insensitive), like grep -v. Entries containing the "<*>" placeholder are matched against the record's masked template instead (excludes a whole dedup group shape).
   */
  exclude?: string[]
  database?: string
  user?: string
  dedup?: boolean
  page_size?: number
  page_token?: string
}
