/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { GetLogsServiceType } from './getLogsServiceType'

export type GetLogsParams = {
  cluster_name: ClusterNameParameter
  service_type: GetLogsServiceType
  from: string
  to: string
  severity?: string[]
  host?: string
  message?: string
  database?: string
  user?: string
  dedup?: boolean
  page_size?: number
  page_token?: string
}
