/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetLogsPlansServiceType =
  (typeof GetLogsPlansServiceType)[keyof typeof GetLogsPlansServiceType]

export const GetLogsPlansServiceType = {
  postgresql: 'postgresql',
  pooler: 'pooler',
} as const
