/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { GetLogsPlansServiceType } from './getLogsPlansServiceType'

export type GetLogsPlansParams = {
  cluster_name: ClusterNameParameter
  service_type: GetLogsPlansServiceType
  from: string
  to: string
  host?: string
  /**
   * keep the plans of this statement only, as a string to preserve int64 precision in JavaScript. A stream whose field map has no query_id role answers 400; GET /api/logs/check lists the role as missing.
   */
  query_id?: string
  /**
   * plan groups the answer carries; the snapshot keeps them all
   */
  limit?: number
}
