/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { GetLogsInsightsServiceType } from './getLogsInsightsServiceType'

export type GetLogsInsightsParams = {
  cluster_name: ClusterNameParameter
  service_type: GetLogsInsightsServiceType
  from: string
  to: string
  host?: string
}
