/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetMaintenanceInfoActivity =
  (typeof GetMaintenanceInfoActivity)[keyof typeof GetMaintenanceInfoActivity]

export const GetMaintenanceInfoActivity = {
  all: 'all',
  active: 'active',
  cold: 'cold',
} as const
