/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { GetMaintenanceInfoActivity } from './getMaintenanceInfoActivity'
import type { InstanceParameter } from './instanceParameter'

export type GetMaintenanceInfoParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  database: DatabaseParameter
  limit?: number
  offset?: number
  /**
   * Filter by table name (case-insensitive substring match)
   */
  table_name?: string
  /**
   * Filter by write activity. "cold" lists tables with no writes for longer than the inactivity threshold; empty when the cold-table marker is unavailable (see /api/maintenance/cold-status).
   */
  activity?: GetMaintenanceInfoActivity
}
