/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { InstanceParameter } from './instanceParameter'

export type GetPgSettingsParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  limit?: number
  offset?: number
}
