/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { InstanceParameter } from './instanceParameter'

export type GetQueriesRunningParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  database: DatabaseParameter
  /**
   * Minimum query duration in seconds
   */
  min_duration?: number
}
