/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { GetQueriesRunningQueryFilterMode } from './getQueriesRunningQueryFilterMode'
import type { InstanceParameter } from './instanceParameter'

export type GetQueriesRunningParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  database: DatabaseParameter
  /**
   * Minimum query duration in seconds
   */
  min_duration?: number
  /**
   * Case-insensitive substring filter for query text. Use SQL wildcards (%, _) explicitly. Empty disables the filter.
   * @maxLength 1000
   */
  query_filter?: string
  /**
   * Filter mode for query_filter — `like` keeps matches, `not_like` excludes them.
   */
  query_filter_mode?: GetQueriesRunningQueryFilterMode
  /**
   * Filter by exact PostgreSQL role name (`usename`).
   * @maxLength 64
   */
  username?: string
}
