/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetQueriesRunningQueryFilterMode =
  (typeof GetQueriesRunningQueryFilterMode)[keyof typeof GetQueriesRunningQueryFilterMode]

export const GetQueriesRunningQueryFilterMode = {
  like: 'like',
  not_like: 'not_like',
} as const
