/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseOptionalParameter } from './databaseOptionalParameter'
import type { InstanceParameter } from './instanceParameter'
import type { ScopeParameter } from './scopeParameter'

export type GetQueriesTop10ChartParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  /**
 * Database whose pg_stat_statements view is read. The extension may be installed in one database only, and in a schema outside search_path; its contents are instance-wide either way. Defaults to any database of the instance that has the extension.

 */
  database?: DatabaseOptionalParameter
  /**
 * Which slice of the instance the answer covers: `database` — only the rows of the named database, `instance` — every database of the host. Defaults to `database` when a database is named and to `instance` otherwise, so callers written before this parameter keep their instance-wide answer. Percentage fields are shares within the chosen scope.

 */
  scope?: ScopeParameter
}
