/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { InstanceParameter } from './instanceParameter'

export type GetQueriesReportParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  /**
   * Comma-separated list of usernames to exclude from the report
   */
  exclude_users?: string[]
}
