/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { GetSchemaLintLevel } from './getSchemaLintLevel'
import type { InstanceParameter } from './instanceParameter'

export type GetSchemaLintParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  database: DatabaseParameter
  /**
   * Keep only findings of this severity. The summary still counts every finding.
   */
  level?: GetSchemaLintLevel
  /**
   * Keep only findings of these checks.
   */
  code?: string[]
  /**
   * Keep only findings in schemas whose name contains this substring, case-insensitively.
   */
  schema?: string
  /**
   * Keep only findings on objects whose name contains this substring, case-insensitively.
   */
  object?: string
  limit?: number
  offset?: number
}
