/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetSchemaLintLevel = (typeof GetSchemaLintLevel)[keyof typeof GetSchemaLintLevel]

export const GetSchemaLintLevel = {
  error: 'error',
  warning: 'warning',
  notice: 'notice',
} as const
