/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type GetTablesHotClass = (typeof GetTablesHotClass)[keyof typeof GetTablesHotClass]

export const GetTablesHotClass = {
  reads: 'reads',
  writes: 'writes',
  io: 'io',
} as const
