/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { InstanceParameter } from './instanceParameter'
import type { DatabaseParameter } from './databaseParameter'

export type GetTablesHitRateParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  database: DatabaseParameter
}
