/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type HealthScoreWeightsSource =
  (typeof HealthScoreWeightsSource)[keyof typeof HealthScoreWeightsSource]

export const HealthScoreWeightsSource = {
  default: 'default',
  override: 'override',
} as const
