/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreCategoryDetails } from './healthScoreCategoryDetails'

export interface HealthScoreCategory {
  name: string
  score: number
  weight: number
  penalty: number
  details: HealthScoreCategoryDetails
}
