/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreFleetItem } from './healthScoreFleetItem'

export interface HealthScoreFleet {
  items: HealthScoreFleetItem[]
  instances_total: number
  instances_scored: number
  /** Instances the metrics prefilter picked for an exact score. */
  candidates: number
  /** Instances left unscored when the time budget ran out. */
  uncomputed: number
  incomplete: boolean
  /** The metrics datasource did not answer; every score comes from the SQL snapshot. */
  metrics_unavailable: boolean
  computed_at: string
  duration_ms: number
}
