/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreHistoryBaseline } from './healthScoreHistoryBaseline'
import type { HealthScoreHistoryDip } from './healthScoreHistoryDip'
import type { HealthScoreHistoryPoint } from './healthScoreHistoryPoint'

export interface HealthScoreHistory {
  points: HealthScoreHistoryPoint[]
  baseline: HealthScoreHistoryBaseline[]
  dips: HealthScoreHistoryDip[]
  baseline_available: boolean
}
