/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreDatabase } from './healthScoreDatabase'

export interface HealthScoreDatabases {
  databases: HealthScoreDatabase[]
  applicable_categories: string[]
  /** @nullable */
  worst_database?: string | null
}
