/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreDatasourceRoleSampleLabels } from './healthScoreDatasourceRoleSampleLabels'

export interface HealthScoreDatasourceRole {
  role: string
  provider: string
  metric: string
  selector: string
  /** Number of matching series (exactly 1 means OK). */
  matched: number
  error?: string
  sample_labels?: HealthScoreDatasourceRoleSampleLabels
}
