/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type HealthScoreRecommendationSeverity =
  (typeof HealthScoreRecommendationSeverity)[keyof typeof HealthScoreRecommendationSeverity]

export const HealthScoreRecommendationSeverity = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
} as const
