/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreRecommendationContext } from './healthScoreRecommendationContext'
import type { HealthScoreRecommendationSeverity } from './healthScoreRecommendationSeverity'

export interface HealthScoreRecommendation {
  rule_id: string
  category: string
  severity: HealthScoreRecommendationSeverity
  metric_value: number
  /**
   * Database the finding belongs to. Null when it is instance-wide and no single database owns it.
   * @nullable
   */
  database?: string | null
  /** @nullable */
  context?: HealthScoreRecommendationContext
  /** @nullable */
  related_route?: string | null
}
