/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreWeightsSource } from './healthScoreWeightsSource'

export interface HealthScoreWeights {
  connections: number
  performance: number
  storage: number
  replication: number
  maintenance: number
  source: HealthScoreWeightsSource
  /** @nullable */
  updated_at?: string | null
  /** @nullable */
  updated_by?: string | null
}
