/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreHistoryPointCategories } from './healthScoreHistoryPointCategories'

export interface HealthScoreHistoryPoint {
  time: string
  score: number
  latency_ms: number
  categories: HealthScoreHistoryPointCategories
}
