/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreRecommendationContext } from './healthScoreRecommendationContext'
import type { HealthScoreRecommendationSeverity } from './healthScoreRecommendationSeverity'

export interface HealthScoreRecommendation {
  rule_id: string
  category: string
  severity: HealthScoreRecommendationSeverity
  metric_value: number
  /** @nullable */
  context?: HealthScoreRecommendationContext
  /** @nullable */
  related_route?: string | null
}
