/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreRecommendation } from './healthScoreRecommendation'

export interface HealthScoreRecommendations {
  recommendations: HealthScoreRecommendation[]
}
