/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HealthScoreTableReloption {
  Schema: string
  Table: string
  RelOptions: string
}
