/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HealthScoreHorizonBlockingSession {
  PID: number
  Username: string
  State: string
  WaitEventType: string
  WaitEvent: string
  XactDurationSeconds: number
  BackendXmin: string
  Query: string
}
