/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HealthScoreHorizonBlockingSession {
  PID: number
  Database: string
  Username: string
  /** pg_stat_activity.backend_type — "autovacuum worker" marks a session that legitimately holds a long snapshot and must not be terminated. */
  BackendType: string
  State: string
  WaitEventType: string
  WaitEvent: string
  XactDurationSeconds: number
  BackendXmin: string
  Query: string
}
