/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HealthScoreLowHotUpdateTable {
  Schema: string
  Table: string
  Updates: number
  HotUpdates: number
  HotRatio: number
}
