/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreDatasourceRole } from './healthScoreDatasourceRole'

export interface HealthScoreDatasourceStatus {
  enabled: boolean
  target: string
  roles: HealthScoreDatasourceRole[]
}
