/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreFleetItemSource } from './healthScoreFleetItemSource'

export interface HealthScoreFleetItem {
  cluster_name: string
  instance: string
  /**
   * Null when the instance was not scored; error says why.
   * @nullable
   */
  score?: number | null
  source: HealthScoreFleetItemSource
  in_recovery: boolean
  metrics_degraded?: boolean
  error?: string
}
