/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HealthScoreHistoryDip {
  time: string
  value: number
  baseline: number
  drop: number
}
