/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HealthScoreWeightsUpdate {
  /** @minimum 0 */
  connections: number
  /** @minimum 0 */
  performance: number
  /** @minimum 0 */
  storage: number
  /** @minimum 0 */
  replication: number
  /** @minimum 0 */
  maintenance: number
  /** @minimum 0 */
  horizon: number
  /** @minimum 0 */
  wal_checkpoint: number
  /** @minimum 0 */
  locks: number
}
