/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type HealthScoreFleetItemSource =
  (typeof HealthScoreFleetItemSource)[keyof typeof HealthScoreFleetItemSource]

export const HealthScoreFleetItemSource = {
  metrics: 'metrics',
  snapshot: 'snapshot',
  none: 'none',
} as const
