/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HealthScoreCategory } from './healthScoreCategory'

export interface HealthScoreDatabase {
  database: string
  size_bytes: number
  score: number
  categories: HealthScoreCategory[]
}
