/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HotEntryDelta } from './hotEntryDelta'
import type { HotHostDelta } from './hotHostDelta'

export interface HotEntry {
  rank: number
  /**
   * Rank in the previous snapshot of the same kind+class; null when the object was not in that top.
   * @nullable
   */
  prev_rank?: number | null
  schema: string
  object: string
  /**
   * For indexes — the table the index belongs to.
   * @nullable
   */
  table_name?: string | null
  size_bytes: number
  /** Cluster-summed counter deltas over the snapshot interval. */
  delta: HotEntryDelta
  /** Class ranking key normalized by the actual window length. */
  rate_per_day: number
  per_host: HotHostDelta[]
}
