/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cluster-summed counter deltas over the snapshot interval.
 */
export type HotEntryDelta = { [key: string]: number }
