/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HotHistogram {
  /** 10th..90th percentiles of the class ranking key across tail objects (outside the top). */
  deciles: number[]
  count: number
  sum: number
  max: number
}
