/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HotHostDeltaDelta } from './hotHostDeltaDelta'

export interface HotHostDelta {
  instance: string
  complete: boolean
  /** True for a standby — its read activity is invisible in the primary's counters. */
  in_recovery: boolean
  delta: HotHostDeltaDelta
}
