/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HotHostWindow {
  from: string
  to: string
  /** False when the host had no baseline or its stats epoch broke (stats reset) — it contributed no deltas. */
  complete: boolean
  /** @nullable */
  stats_reset?: string | null
}
