/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HotObjectHistoryItem } from './hotObjectHistoryItem'

export interface HotObjectHistory {
  items: HotObjectHistoryItem[]
}
