/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HotObjectHistoryItemDelta } from './hotObjectHistoryItemDelta'

export interface HotObjectHistoryItem {
  captured_at: string
  class: string
  rank: number
  size_bytes: number
  delta: HotObjectHistoryItemDelta
}
