/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface HotPercentile {
  /** Share of tail objects this object currently out-runs (0..0.9 from the histogram; combined with in_top for the exact upper range). */
  percentile: number
  rate_per_day: number
  /** Whether the object is in the latest stored top of this class. */
  in_top: boolean
  class: string
}
