/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HotEntry } from './hotEntry'
import type { HotSnapshotMeta } from './hotSnapshotMeta'

export interface HotReport {
  snapshot: HotSnapshotMeta
  entries: HotEntry[]
}
