/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { HotHistogram } from './hotHistogram'
import type { HotSnapshotMetaWindows } from './hotSnapshotMetaWindows'

export interface HotSnapshotMeta {
  captured_at: string
  windows: HotSnapshotMetaWindows
  /** Hosts that could not be sampled — the snapshot is partial, their activity is absent from every number. */
  hosts_missing: string[]
  /** sum(top)/sum(all) for the requested kind+class — how representative the stored top is. */
  coverage: number
  histogram?: HotHistogram | null
  /** Capture timestamps available for the day selector, newest first. */
  dates: string[]
}
