/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorMessage } from './errorMessage'

/**
 * The two sides cannot be matched against each other: one names the database of every statement and the other does not, because it was stored before per-database attribution existed (json_version 1). A queryid alone does not identify a statement across databases, so pairing them would invent matches. Compare two snapshots of the same generation instead — live statistics always count as the newer one.

 */
export type IncomparableSnapshotsResponse = ErrorMessage
