/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IndexSimilar3 {
  Table: string
  I1IndexName: string
  I2IndexName: string
  SimplifiedIndexDefinition: string
  I1IndexDefinition: string
  I2IndexDefinition: string
  I1UsedInConstraint: string
  I2UsedInConstraint: string
}
