/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IndexAdvisorCoveredQuery } from './indexAdvisorCoveredQuery'
import type { IndexAdvisorWarning } from './indexAdvisorWarning'
import type { IndexAdvisorWrites } from './indexAdvisorWrites'

export interface IndexAdvisorCandidate {
  schema: string
  /** Table the index belongs on. For a partitioned table this is always the root, whichever partition the statement named — PostgreSQL propagates the index down. */
  table: string
  /** Key columns in order: equality predicates first, then at most one range predicate, then ordering columns when a range predicate did not already break the ordering. */
  columns: string[]
  /** Statement suggested to the user. CONCURRENTLY unless the table is partitioned, where PostgreSQL rejects it. Dasha never executes DDL. */
  ddl: string
  /** Share of the analyzed execution time spent in the statements this candidate covers. It is the size of the problem, NOT a predicted gain — no planner has confirmed the index would be used at all. */
  weight_pct: number
  covered_queries: IndexAdvisorCoveredQuery[]
  /** reltuples, summed over the partitions for a partitioned table. */
  table_rows: number
  writes: IndexAdvisorWrites
  /** Reasons this candidate may be a bad idea despite ranking well. */
  warnings: IndexAdvisorWarning[]
  /** False throughout this step. A client must carry the caveat: the recommendation is structural, derived from the statements and the catalog alone. */
  planner_checked: boolean
}
