/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IndexInvalidOrNotReady {
  Table: string
  IndexName: string
  IsValid: boolean
  IsReady: boolean
  Constraint: string
}
