/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IndexAdvisorCandidate } from './indexAdvisorCandidate'
import type { IndexAdvisorNotParsed } from './indexAdvisorNotParsed'
import type { IndexAdvisorSummary } from './indexAdvisorSummary'

export interface IndexAdvisorReport {
  /** Proposed indexes, heaviest share of execution time first. */
  candidates: IndexAdvisorCandidate[]
  /** Why part of the workload produced nothing, counted per reason. One entry per statement, so the counts sum to the number of statements that contributed no candidate. A client must show this next to the candidate list: an empty list with a large count here means the analysis fell short, not that the schema is in good shape. */
  not_parsed: IndexAdvisorNotParsed[]
  summary: IndexAdvisorSummary
  /** Hosts of the cluster whose pg_stat_statements could not be read. Their load never entered the analysis, so the candidate list is incomplete by exactly that much — not merely shorter. A client must show this: statements running only on an unread host produce no candidate at all, and nothing else in the response says so. */
  unreachable_hosts: string[]
  /** Candidates before pagination. */
  total: number
  duration_ms: number
}
