/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IndexHostUsage {
  instance: string
  /** True for a standby — usage seen only here must not be dropped. */
  in_recovery: boolean
  index_scans: number
  /** Days of statistics the scan counter on this host covers. */
  window_days: number
  /** index_scans normalized over window_days — the only comparable unit. */
  scans_per_day: number
  /** False when the database's statistics were never reset: window_days then falls back to postmaster uptime, which understates the true window. */
  stats_reset_known: boolean
}
