/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IndexT {
  Schema: string;
  Table: string;
  Name: string;
  Columns: string;
  Using: string;
  Unique: boolean;
  Primary: boolean;
  Valid: boolean;
  Indexprs: string;
  Indpred: string;
  Definition: string;
}
