/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The queryid this statement carries on each host it was read from, keyed by host. query_ids and hosts are two separate lists once the rows are folded, so a client that needs a queryid a given host will actually recognize — a deep link into the per-instance query report — must read it from here instead of pairing the two lists by position.
 */
export type IndexAdvisorCoveredQueryQueryIdByHost = { [key: string]: string }
