/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IndexHostUsage } from './indexHostUsage'
import type { IndexVerdictReasonCode } from './indexVerdictReasonCode'
import type { IndexVerdictReasonNotesItem } from './indexVerdictReasonNotesItem'
import type { IndexVerdictReasonParams } from './indexVerdictReasonParams'
import type { IndexVerdictVerdict } from './indexVerdictVerdict'

export interface IndexVerdict {
  schema: string
  table: string
  /** The index a DROP must target. For a partitioned index this is the top-level parent, never a partition's child: PostgreSQL refuses to drop a child and its HINT points at the parent, and dropping that strips the index off EVERY partition. */
  index: string
  /** True when this is a partitioned index: the scans of its per-partition child indexes are summed into this verdict, so one busy partition keeps the whole index alive. A cold partition showing zero scans is partition pruning working, not a dead index — which is why children are never judged on their own. */
  partitioned: boolean
  /** How many per-partition child indexes were summed into this verdict. */
  partitions?: number
  /** Largest copy across hosts — what a DROP would actually reclaim. */
  size_bytes: number
  verdict: IndexVerdictVerdict
  /** Why this verdict, in words, quoting the observed window and scan rate. English only, and rendered from reason_code and reason_params — a UI that localizes builds its own sentence from those instead. */
  reason: string
  /** Machine-readable form of reason. The numbers it quotes are in reason_params. */
  reason_code: IndexVerdictReasonCode
  reason_params: IndexVerdictReasonParams
  /** Caveats that qualify the verdict without changing it, rendered after the reason. "partitioned" quotes the partitions field. */
  reason_notes?: IndexVerdictReasonNotesItem[]
  per_instance: IndexHostUsage[]
}
