/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * found — plans over the window scan this table sequentially while running the statements the candidate covers. not_found — the plans were read and none of them does, which is an argument against the index. not_searched — nothing looked: evidence is off, the cluster has no log source, the store did not answer, or the window holds no plan at all. A client must not render not_searched as not_found; the first says nothing about the database.
 */
export type IndexAdvisorEvidenceState =
  (typeof IndexAdvisorEvidenceState)[keyof typeof IndexAdvisorEvidenceState]

export const IndexAdvisorEvidenceState = {
  not_searched: 'not_searched',
  not_found: 'not_found',
  found: 'found',
} as const
