/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Machine-readable form of reason. The numbers it quotes are in reason_params.
 */
export type IndexVerdictReasonCode =
  (typeof IndexVerdictReasonCode)[keyof typeof IndexVerdictReasonCode]

export const IndexVerdictReasonCode = {
  unreachable_hosts: 'unreachable_hosts',
  no_evidence: 'no_evidence',
  used_on_replica_only: 'used_on_replica_only',
  used: 'used',
  window_too_short: 'window_too_short',
  few_scans: 'few_scans',
  never_scanned: 'never_scanned',
} as const
