/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IndexTopKBySize {
  Tablespace: string
  Table: string
  Index: string
  Size: string
  SizeBytes: number
}
