/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IndexAdvisorSummary {
  /** False when pg_stat_statements could not be read at all, which is a different statement from having read it and found nothing. */
  pgss_available: boolean
  /** Statements read and parsed. */
  analyzed_queries: number
  /** Units of work left after folding statements by fingerprint. */
  collapsed_groups: number
  not_parsed_count: number
  /** Share of analyzed execution time the candidates touch. Statements covered twice count once — this is how much of the load is in scope, not how much would be saved. */
  covered_time_pct: number
  /** The catalog was read only in part, so a candidate may duplicate an index that was never read. */
  catalog_truncated: boolean
}
