/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * What maintaining an index on this table would cost, from pg_stat_user_tables. Scans are the other side of the trade: they are what an index would serve.
 */
export interface IndexAdvisorWrites {
  inserted: number
  updated: number
  deleted: number
  seq_scans: number
  idx_scans: number
}
