/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IndexVerdict } from './indexVerdict'

export interface IndexUnusedReport {
  indexes: IndexVerdict[]
  /** Hosts of the cluster that could not be read. A non-empty list forces every verdict to "unknown": scan counters are not replicated, so an index idle on the hosts that answered may be serving reads on one that did not. */
  unreachable_hosts: string[]
}
