/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IndexSimilar1 {
  Table: string
  I1UniqueIndexName: string
  I2IndexName: string
  I1UniqueIndexDefinition: string
  I2IndexDefinition: string
  I1UsedInConstraint: string
  I2UsedInConstraint: string
}
