/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type IndexVerdictReasonNotesItem =
  (typeof IndexVerdictReasonNotesItem)[keyof typeof IndexVerdictReasonNotesItem]

export const IndexVerdictReasonNotesItem = {
  stats_reset_never: 'stats_reset_never',
  partitioned: 'partitioned',
} as const
