/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IndexVerdictHostRate } from './indexVerdictHostRate'

/**
 * The values a reason quotes. Which fields are set depends on reason_code — a client reads only the ones its phrasing for that code needs.
 */
export interface IndexVerdictReasonParams {
  /** Hosts that could not be read — set for unreachable_hosts. */
  hosts?: string[]
  /** Hosts scanning the index often enough to keep it — set for used and used_on_replica_only. */
  used_on?: IndexVerdictHostRate[]
  /** Shortest statistics window across the hosts the verdict weighed. */
  window_days?: number
  /** Window below which no verdict is given — set for window_too_short. */
  min_window_days?: number
  /** Scans summed over every host — set for few_scans. */
  total_scans?: number
  /** How many hosts reported zero scans — set for never_scanned. */
  host_count?: number
}
