/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IndexAdvisorEvidenceState } from './indexAdvisorEvidenceState'

/**
 * What the plans auto_explain wrote over a recent window say about this candidate. Off unless log_insights.index_advisor_evidence is set, and silent whenever the log source cannot be read: the report is built from pg_stat_statements and the catalog alone, exactly as it is on a cluster with no logs at all.
 */
export interface IndexAdvisorEvidence {
  /** found — plans over the window scan this table sequentially while running the statements the candidate covers. not_found — every plan of the window was read and none of them does, which is an argument against the index. not_searched — nothing looked or nothing conclusive came back: evidence is off, the cluster has no log source, the store did not answer, the window holds no plan at all, only part of it could be read, or a scan of this table name carries no schema while the report holds the name in two. A client must not render not_searched as not_found; the first says nothing about the database. */
  state: IndexAdvisorEvidenceState
  /** Plan records over the window that scan this table sequentially, counted per record rather than per shape. */
  plans?: number
  /** Sequential scans of this table across the sampled plans — one sample per shape, the slowest of it. */
  seq_scan_nodes?: number
  /** Time those nodes spent, across all loops, summed over the sampled plans. It is the weight of the sampled executions, NOT extrapolated to every record behind them. Zero where auto_explain.log_analyze is off: the scans are known, their cost is not. */
  actual_time_ms?: number
  /** Rows the filters of those nodes discarded, across all loops. */
  rows_removed?: number
  window_from?: string
  window_to?: string
  /** The window was read only in part — the scan hit its record or byte budget, or the store gave up — so every count here is a lower bound. */
  partial?: boolean
}
