/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IndexBloat {
  Schema: string
  Table: string
  Index: string
  BloatBytes: number
  IndexBytes: number
  Definition: string
  Primary: boolean
}
