/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IndexAdvisorCoveredQueryQueryIdByHost } from './indexAdvisorCoveredQueryQueryIdByHost'

export interface IndexAdvisorCoveredQuery {
  /** Every pg_stat_statements row folded into this unit, as strings to preserve int64 precision in JavaScript. More than one means the same statement was recorded several times — different roles, or an extension that keys its view by plan as well. */
  query_ids: string[]
  /** The queryid this statement carries on each host it was read from, keyed by host. query_ids and hosts are two separate lists once the rows are folded, so a client that needs a queryid a given host will actually recognize — a deep link into the per-instance query report — must read it from here instead of pairing the two lists by position. */
  query_id_by_host: IndexAdvisorCoveredQueryQueryIdByHost
  /** Hash of the statement structure, stable across constants and formatting. */
  fingerprint: string
  /** Normalized statement text, sanitized. */
  query: string
  weight_pct: number
  calls: number
  /** Hosts of the cluster this statement was read from. A candidate whose statements run only on the replicas is still worth creating — the index is replicated — but the primary is not where the gain lands, and only this says so. */
  hosts: string[]
}
