/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface InvalidConstraint {
  Schema: string
  Table: string
  Name: string
  ReferencedSchema: string
  ReferencedTable: string
}
