/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface IOHistoryMeta {
  instance: string
  /**
   * Oldest stored capture of this host — from when history exists at all.
   * @nullable
   */
  earliest_at?: string | null
  /** @nullable */
  latest_at?: string | null
  /** Value at the newest capture in the period. */
  track_io_timing: boolean
  /** The setting was toggled inside the period, so I/O times cover only part of it. */
  track_io_timing_changed: boolean
  /** The server was upgraded inside the period; the intervals spanning the upgrade are incomplete. */
  version_changed: boolean
}
