/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IOHistoryMeta } from './iOHistoryMeta'
import type { IOSeries } from './iOSeries'

export interface IOHistory {
  meta: IOHistoryMeta
  series: IOSeries[]
}
