/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IOPointValues } from './iOPointValues'

export interface IOPoint {
  from: string
  to: string
  /** Measured length of the summed intervals — the denominator for any rate. Zero when no interval in the bucket was complete. */
  duration_seconds: number
  /** False when a broken epoch fell into this bucket; draw a gap, not a zero. */
  complete: boolean
  values: IOPointValues
}
