/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Counters, plus I/O times in milliseconds when track_io_timing is on. Absent counters are the ones the server reports as NULL.
 */
export type IORowValues = { [key: string]: number }
