/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IORowValues } from './iORowValues'

export interface IORow {
  backend_type: string
  object: string
  context: string
  /** Counters, plus I/O times in milliseconds when track_io_timing is on. Absent counters are the ones the server reports as NULL. */
  values: IORowValues
}
