/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The dimensions this series keeps. The ones it was summed over are absent.
 */
export interface IOSeriesKey {
  backend_type?: string
  object?: string
  context?: string
}
