/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IOPoint } from './iOPoint'
import type { IOSeriesKey } from './iOSeriesKey'

export interface IOSeries {
  key: IOSeriesKey
  points: IOPoint[]
}
