/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IORow } from './iORow'

export interface IOSnapshot {
  instance: string
  captured_at: string
  /** server_version_num at capture time — it decides how the counters are read. */
  version_num: number
  /**
   * Fixed operation size reported by PostgreSQL 16/17; null from 18 on, where the server reports byte counters directly.
   * @nullable
   */
  op_bytes?: number | null
  /** When false the server collects no I/O times and the Time metrics are absent. */
  track_io_timing: boolean
  /**
   * The pg_stat_io epoch; a change between two snapshots invalidates the interval between them.
   * @nullable
   */
  stats_reset?: string | null
  rows: IORow[]
}
