/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { IncludeRevokedParameter } from './includeRevokedParameter'

export type ListAllPersonalTokensParams = {
  /**
   * Include revoked tokens in the listing. They are kept as an audit trail and can never authenticate again.
   */
  include_revoked?: IncludeRevokedParameter
}
