/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LockBackgroundPeak } from './lockBackgroundPeak'
import type { QueryBlocked } from './queryBlocked'

/**
 * Lock graph captured alongside an auto-snapshot (snapshots.locks_data).
 */
export interface LockSnapshot {
  captured: boolean
  probes?: number
  /** Go duration string between probes */
  probe_interval?: string
  /** @nullable */
  harshest_at?: string | null
  /** Distinct blocked sessions in the harshest probe */
  blocked_count: number
  max_wait_ms?: number
  background_peak?: LockBackgroundPeak
  rows?: QueryBlocked[]
  error?: string
}
