/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogInsights } from './logInsights'

/**
 * One side of a comparison. The baseline side is absent when the current window found no plan: there was nothing to compare it against, so it was not read. The summary of a window carries no plan groups; read them by its scan_id.
 */
export interface LogComparedWindow {
  from: string
  to: string
  summary: LogInsights
}
