/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogCategoryCode } from './logCategoryCode'
import type { LogCategoryTemplate } from './logCategoryTemplate'

export interface LogCategory {
  /** Matched by SQLSTATE where the stream carries it, then by the record itself (an auto_explain plan, a statement duration), then by the English message text. other is whatever matched nothing. */
  code: LogCategoryCode
  count: number
  /** fraction of the records read, 0..1 */
  share: number
  first_seen: string
  last_seen: string
  /** most frequent message templates, variable parts replaced with <*>; empty for plan */
  templates: LogCategoryTemplate[]
}
