/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Matched by SQLSTATE where the stream carries it, then by the record itself (an auto_explain plan, a statement duration), then by the English message text. other is whatever matched nothing.
 */
export type LogCategoryCode = (typeof LogCategoryCode)[keyof typeof LogCategoryCode]

export const LogCategoryCode = {
  deadlock: 'deadlock',
  lock_wait: 'lock_wait',
  connection_limit: 'connection_limit',
  authentication: 'authentication',
  canceled: 'canceled',
  plan: 'plan',
  slow_query: 'slow_query',
  checkpoint: 'checkpoint',
  autovacuum: 'autovacuum',
  temp_file: 'temp_file',
  connection: 'connection',
  error: 'error',
  other: 'other',
} as const
