/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogEntryFields } from './logEntryFields'

export interface LogEntry {
  timestamp: string
  severity?: string
  hostname?: string
  /** primary message field, masked */
  text?: string
  database?: string
  user?: string
  /** full masked message map (for detail expand) */
  fields?: LogEntryFields
  /** dedup only - number of matched records in the group */
  count?: number
  /** dedup only */
  first_seen?: string
  /** dedup only */
  last_seen?: string
}
