/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogCategory } from './logCategory'
import type { LogInsightsPartialReason } from './logInsightsPartialReason'
import type { LogPlanConfiguration } from './logPlanConfiguration'
import type { LogPlansSummary } from './logPlansSummary'
import type { LogScanInfo } from './logScanInfo'

/**
 * One read of a window, by GET /api/logs/insights or GET /api/logs/plans.
 */
export interface LogInsights {
  /** records read from the window */
  scanned: number
  /** the summary covers less than the whole window */
  partial: boolean
  partial_reasons: LogInsightsPartialReason[]
  /** earliest record read; absent when nothing was read. A scan cut by its budget keeps the newest records on VictoriaLogs and the oldest on OpenSearch. */
  covered_from?: string
  /** latest record read; absent when nothing was read */
  covered_to?: string
  /** event categories seen in the window, most frequent first; absent on a plans scan, which reads the window for plan records alone */
  categories?: LogCategory[]
  /** what the log store filtered on itself, so an empty result is not mistaken for an empty window: severity=<values> is the level auto_explain logs with, query_id an exact match on the statement id, text the phrase of a plan record. A store that cannot run a filter without dropping matching records leaves it out and Dasha scans wider. */
  narrowed_by?: string[]
  configuration?: LogPlanConfiguration
  plans: LogPlansSummary
  /** the snapshot this summary was stored as; absent when no snapshot storage is configured or the write failed. Refine it through GET /api/logs/scans/{scan_id}. */
  scan_id?: string
  scan?: LogScanInfo
}
