/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * records and bytes - the scan budget of log_insights ran out; timeout - the source did not answer in time; source - the source stopped before the end of the window; plans - max_plans plan records were parsed and the rest were only counted.
 */
export type LogInsightsPartialReason =
  (typeof LogInsightsPartialReason)[keyof typeof LogInsightsPartialReason]

export const LogInsightsPartialReason = {
  records: 'records',
  bytes: 'bytes',
  timeout: 'timeout',
  source: 'source',
  plans: 'plans',
} as const
