/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogCategory } from './logCategory'
import type { LogInsightsPartialReason } from './logInsightsPartialReason'
import type { LogPlansSummary } from './logPlansSummary'

export interface LogInsights {
  /** records read from the window */
  scanned: number
  /** the summary covers less than the whole window */
  partial: boolean
  partial_reasons: LogInsightsPartialReason[]
  /** earliest record read; absent when nothing was read. A scan cut by its budget keeps the newest records on VictoriaLogs and the oldest on OpenSearch. */
  covered_from?: string
  /** latest record read; absent when nothing was read */
  covered_to?: string
  /** event categories seen in the window, most frequent first */
  categories: LogCategory[]
  plans: LogPlansSummary
}
