/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * off leaves every plan record without a statement id, so plans cannot be tied to the query report
 */
export type LogPlanConfigurationComputeQueryId =
  (typeof LogPlanConfigurationComputeQueryId)[keyof typeof LogPlanConfigurationComputeQueryId]

export const LogPlanConfigurationComputeQueryId = {
  off: 'off',
  on: 'on',
  auto: 'auto',
  regress: 'regress',
} as const
