/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogPlanGroup } from './logPlanGroup'
import type { LogPlansSummaryEmptyReason } from './logPlansSummaryEmptyReason'
import type { PlanDormantRule } from './planDormantRule'
import type { PlanNotParsed } from './planNotParsed'

export interface LogPlansSummary {
  /** auto_explain records found, parsed or not */
  records: number
  parsed: number
  not_parsed: PlanNotParsed[]
  /** parsed plans whose record carries no query_id */
  without_query_id: number
  total_groups: number
  /** earliest record read while the plan budget lasted; equals the scan span unless max_plans ran out */
  covered_from?: string
  /** latest record read while the plan budget lasted */
  covered_to?: string
  total_duration_ms: number
  max_duration_ms: number
  first_seen?: string
  last_seen?: string
  /** the groups among the top by total time or among the top by slowest run, ordered by total time */
  groups: LogPlanGroup[]
  /** rules that could not run on some groups, and what those plans lacked */
  dormant: PlanDormantRule[]
  /** set when groups is empty */
  empty_reason?: LogPlansSummaryEmptyReason
}
