/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogPlanGroupRow } from './logPlanGroupRow'

export interface LogPlanGroupPage {
  /** groups the scan holds, after query_id is applied */
  total: number
  items: LogPlanGroupRow[]
}
