/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * auto_explain.log_format; Dasha parses text and json
 */
export type LogPlanConfigurationLogFormat =
  (typeof LogPlanConfigurationLogFormat)[keyof typeof LogPlanConfigurationLogFormat]

export const LogPlanConfigurationLogFormat = {
  text: 'text',
  json: 'json',
  xml: 'xml',
  yaml: 'yaml',
} as const
