/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PlanDurationStats } from './planDurationStats'
import type { PlanFinding } from './planFinding'

/**
 * a plan group without its plan tree
 */
export interface LogPlanGroupRow {
  /** rank of the group by total time within the scan */
  ord: number
  /** query_id of the log record as string to preserve int64 precision in JavaScript; absent when the record has none */
  query_id?: string
  /** plan shape fingerprint */
  hash: string
  count: number
  durations: PlanDurationStats
  first_seen: string
  last_seen: string
  query_text: string
  /** bytes of query_text left out of the response */
  query_text_omitted_bytes?: number
  findings: PlanFinding[]
}
