/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PlanDurationStats } from './planDurationStats'
import type { PlanSummary } from './planSummary'

/**
 * Plans of one statement with one shape. Nested statements share the query_id of the statement that ran them, so the normalized query text is part of the grouping.
 */
export interface LogPlanGroup {
  /** query_id of the log record as string to preserve int64 precision in JavaScript; absent when the record has none */
  query_id?: string
  /** plan shape fingerprint */
  hash: string
  count: number
  durations: PlanDurationStats
  first_seen: string
  last_seen: string
  plan: PlanSummary
}
