/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type LogPlanRegressionSeverity =
  (typeof LogPlanRegressionSeverity)[keyof typeof LogPlanRegressionSeverity]

export const LogPlanRegressionSeverity = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
} as const
