/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogPlanRegressionReason } from './logPlanRegressionReason'
import type { LogPlanRegressionSeverity } from './logPlanRegressionSeverity'
import type { PlanDurationStats } from './planDurationStats'

/**
 * One statement whose plans differ between the windows. current and baseline hold the durations of the shape that took the most time in each window: percentiles of two shapes cannot be merged after the fact.
 */
export interface LogPlanRegression {
  /** query_id of the log record as string to preserve int64 precision in JavaScript; absent when the records carry none, and the statement is then tied to the baseline window by its normalized text */
  query_id?: string
  query_text: string
  /** bytes of query_text left out of the response */
  query_text_omitted_bytes?: number
  reasons: LogPlanRegressionReason[]
  severity: LogPlanRegressionSeverity
  added_hashes: string[]
  removed_hashes: string[]
  added_indexes: string[]
  lost_indexes: string[]
  current: PlanDurationStats
  baseline: PlanDurationStats
  /** plans of the dominant shape in the current window, which is what its percentiles and the ratios are measured over */
  current_count: number
  /** plans of the dominant shape in the baseline window */
  baseline_count: number
  /** current p50 over baseline p50; 0 when the baseline measured nothing */
  p50_ratio: number
  /** current p95 over baseline p95; 0 when the baseline measured nothing */
  p95_ratio: number
}
