/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogComparedWindow } from './logComparedWindow'
import type { LogPlanRegression } from './logPlanRegression'

/**
 * Two windows of plans side by side, by GET /api/logs/plans/compare.
 */
export interface LogPlanComparison {
  /** one of the two windows was cut short by a limit or a timeout, so the ratios compare two samples of unknown size */
  partial: boolean
  current: LogComparedWindow
  baseline?: LogComparedWindow
  /** statements whose plans changed for the worse, worst first */
  regressions: LogPlanRegression[]
}
