/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * set when groups is empty
 */
export type LogPlansSummaryEmptyReason =
  (typeof LogPlansSummaryEmptyReason)[keyof typeof LogPlansSummaryEmptyReason]

export const LogPlansSummaryEmptyReason = {
  no_records: 'no_records',
  no_plan_records: 'no_plan_records',
  unsupported_plan_format: 'unsupported_plan_format',
  not_parsed: 'not_parsed',
  budget_exhausted: 'budget_exhausted',
  source_unavailable: 'source_unavailable',
} as const
