/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogPlanConfigurationComputeQueryId } from './logPlanConfigurationComputeQueryId'
import type { LogPlanConfigurationLogFormat } from './logPlanConfigurationLogFormat'

/**
 * What pg_settings says about plan logging on one host of the cluster. Absent when no host answered: the setup is a diagnosis, not a precondition of the scan.
 */
export interface LogPlanConfiguration {
  /** the host these settings were read from */
  instance: string
  /** auto_explain is loaded, so it registers its settings. With it off no plan reaches the log and the rest of this block is absent. */
  auto_explain: boolean
  /** auto_explain.log_min_duration: statements faster than this are not logged. -1 logs nothing, 0 logs every statement. */
  log_min_duration_ms?: number
  /** auto_explain.log_analyze: off leaves the plan without measured rows and times, and the checks that need them do not run. */
  log_analyze?: boolean
  /** auto_explain.log_format; Dasha parses text and json */
  log_format?: LogPlanConfigurationLogFormat
  /** auto_explain.log_level, the severity the plans carry in the log */
  log_level?: string
  /** off leaves every plan record without a statement id, so plans cannot be tied to the query report */
  compute_query_id?: LogPlanConfigurationComputeQueryId
}
