/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogSourceCheckFieldTypes } from './logSourceCheckFieldTypes'
import type { LogSourceCheckFound } from './logSourceCheckFound'
import type { LogSourceCheckSample } from './logSourceCheckSample'

export interface LogSourceCheck {
  /** name of the log source serving the cluster */
  source: string
  stream: string
  /** resolved upstream location - an index pattern or a cluster id */
  target: string
  /** records the source holds for the cluster in the last hour */
  documents?: number
  /** field map roles bound to a field present upstream */
  found?: LogSourceCheckFound
  /** roles whose field is absent upstream */
  missing?: string[]
  /** type the store indexes each mapped field as */
  field_types?: LogSourceCheckFieldTypes
  /** one masked record from the window */
  sample?: LogSourceCheckSample
}
