/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * field map roles bound to a field present upstream
 */
export type LogSourceCheckFound = { [key: string]: string }
