/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogEntry } from './logEntry'

export interface LogSearchResult {
  items: LogEntry[]
  /** present only when not deduped and more records are available */
  next_page_token?: string
  dedup: boolean
  /** max_scan reached - results/counts are incomplete */
  partial: boolean
  scanned?: number
}
