/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * type the store indexes each mapped field as
 */
export type LogSourceCheckFieldTypes = { [key: string]: string }
