/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type LogScanInfoServiceType =
  (typeof LogScanInfoServiceType)[keyof typeof LogScanInfoServiceType]

export const LogScanInfoServiceType = {
  postgresql: 'postgresql',
  pooler: 'pooler',
} as const
