/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * one masked record from the window
 */
export type LogSourceCheckSample = { [key: string]: string }
