/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { LogScanInfoKind } from './logScanInfoKind'
import type { LogScanInfoServiceType } from './logScanInfoServiceType'

/**
 * what a stored scan read; present when the summary comes from a snapshot
 */
export interface LogScanInfo {
  kind: LogScanInfoKind
  cluster_name: string
  service_type: LogScanInfoServiceType
  host?: string
  from: string
  to: string
  created_at: string
}
