/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type LogScanInfoKind = (typeof LogScanInfoKind)[keyof typeof LogScanInfoKind]

export const LogScanInfoKind = {
  insights: 'insights',
  plans: 'plans',
  compare: 'compare',
} as const
