/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface MaintenanceInfo {
  Schema: string;
  Table: string;
  /** @nullable */
  LastVacuum: string | null;
  /** @nullable */
  LastAutovacuum: string | null;
  /** @nullable */
  LastAnalyze: string | null;
  /** @nullable */
  LastAutoanalyze: string | null;
  DeadRows: number;
  LiveRows: number;
}
