/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface MaintenanceAutovacuumSummary {
  /** Tables past the autovacuum trigger (dead-tuple or insert formula) but not the autoanalyze one. */
  TablesDueVacuumOnly: number
  /** Tables past the autoanalyze trigger only. */
  TablesDueAnalyzeOnly: number
  /** Tables past both triggers. */
  TablesDueBoth: number
  /** Total user tables considered. */
  TablesTotal: number
  /** VACUUM processes currently running in the database (pg_stat_progress_vacuum). */
  RunningVacuums: number
  /** ANALYZE processes currently running in the database (pg_stat_progress_analyze). */
  RunningAnalyzes: number
}
