/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface MaintenanceInfo {
  Schema: string
  Table: string
  /** @nullable */
  LastVacuum: string | null
  /** @nullable */
  LastAutovacuum: string | null
  /** @nullable */
  LastAnalyze: string | null
  /** @nullable */
  LastAutoanalyze: string | null
  DeadRows: number
  LiveRows: number
  /**
   * Whole days without writes; null unless the table is cold.
   * @nullable
   */
  NoWritesDays?: number | null
}
