/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorMessage } from './errorMessage'

/**
 * Another transaction holds a lock that blocks reading the object (ALTER TABLE, VACUUM FULL, REINDEX, a transaction left open). The query was cancelled by lock_timeout rather than left waiting; retry later.

 */
export type ObjectLockedResponse = ErrorMessage
