/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PersonalAccessTokenCreateRole } from './personalAccessTokenCreateRole'

export interface PersonalAccessTokenCreate {
  /** Human-readable label for the token. */
  name: string
  /** Token role; must not exceed the caller's role. Defaults to viewer. */
  role?: PersonalAccessTokenCreateRole
  /**
   * Optional lifetime in days (max 3650 = 10 years); omitted or 0 means no expiry. Admin tokens are an exception: they are always capped at 30 days, and cannot be issued without an expiry — a request for a longer (or absent) lifetime is clamped rather than rejected, so check expires_at in the response for the value actually applied.
   * @minimum 0
   * @maximum 3650
   */
  expires_in_days?: number
}
