/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PersonalAccessTokenCreatedRole } from './personalAccessTokenCreatedRole'

export interface PersonalAccessTokenCreated {
  id: string
  name: string
  prefix: string
  role: PersonalAccessTokenCreatedRole
  /** The full secret. Returned only once, at creation. */
  token: string
  created_at: string
  /** @nullable */
  expires_at?: string | null
}
