/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type PersonalAccessTokenRole =
  (typeof PersonalAccessTokenRole)[keyof typeof PersonalAccessTokenRole]

export const PersonalAccessTokenRole = {
  viewer: 'viewer',
  admin: 'admin',
} as const
