/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type PersonalAccessTokenCreatedRole =
  (typeof PersonalAccessTokenCreatedRole)[keyof typeof PersonalAccessTokenCreatedRole]

export const PersonalAccessTokenCreatedRole = {
  viewer: 'viewer',
  admin: 'admin',
} as const
