/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Token role; must not exceed the caller's role. Defaults to viewer.
 */
export type PersonalAccessTokenCreateRole =
  (typeof PersonalAccessTokenCreateRole)[keyof typeof PersonalAccessTokenCreateRole]

export const PersonalAccessTokenCreateRole = {
  viewer: 'viewer',
  admin: 'admin',
} as const
