/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PersonalAccessTokenRole } from './personalAccessTokenRole'

export interface PersonalAccessToken {
  id: string
  name: string
  /** Token prefix shown for identification (not the secret). */
  prefix: string
  role: PersonalAccessTokenRole
  created_at: string
  /** @nullable */
  last_used_at?: string | null
  /** @nullable */
  expires_at?: string | null
}
