/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PlanMissingRequirement } from './planMissingRequirement'

export interface PlanDormantRule {
  code: string
  /** what the plan lacked for the rule to run */
  missing: PlanMissingRequirement[]
  /** in a summary, how many plan groups the rule could not run on */
  groups?: number
}
