/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * exact over the plans of the group; percentiles by nearest rank
 */
export interface PlanDurationStats {
  min_ms: number
  p50_ms: number
  p95_ms: number
  max_ms: number
  sum_ms: number
}
