/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PlanCapabilities } from './planCapabilities'
import type { PlanDormantRule } from './planDormantRule'
import type { PlanFinding } from './planFinding'
import type { PlanJIT } from './planJIT'
import type { PlanNode } from './planNode'
import type { PlanSummaryFormat } from './planSummaryFormat'
import type { PlanSummarySettings } from './planSummarySettings'
import type { PlanTrigger } from './planTrigger'

/**
 * One parsed plan with the rules evaluated on it.
 */
export interface PlanSummary {
  format: PlanSummaryFormat
  /** built with GENERIC_PLAN, parameters not substituted */
  generic: boolean
  /** at most 8 KiB; query_text_omitted_bytes counts the rest */
  query_text: string
  /** bytes cut from the end of query_text; absent when it is complete */
  query_text_omitted_bytes?: number
  /** at most 8 KiB; query_params_omitted_bytes counts the rest */
  query_params?: string
  /** bytes cut from the end of query_params; absent when it is complete */
  query_params_omitted_bytes?: number
  /** known for a plan taken from a log record */
  duration_ms?: number
  planning_time_ms?: number
  execution_time_ms?: number
  capabilities: PlanCapabilities
  root: PlanNode
  triggers?: PlanTrigger[]
  jit?: PlanJIT
  settings?: PlanSummarySettings
  /** most severe first */
  findings: PlanFinding[]
  dormant: PlanDormantRule[]
}
