/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * unsupported_plan_format - xml or yaml; empty_plan; parse_error; plan_too_large - larger than max_plan_bytes; plan_budget_exhausted - past max_plans.
 */
export type PlanNotParsedCode = (typeof PlanNotParsedCode)[keyof typeof PlanNotParsedCode]

export const PlanNotParsedCode = {
  unsupported_plan_format: 'unsupported_plan_format',
  empty_plan: 'empty_plan',
  parse_error: 'parse_error',
  plan_too_large: 'plan_too_large',
  plan_budget_exhausted: 'plan_budget_exhausted',
} as const
