/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type PlanFindingSeverity = (typeof PlanFindingSeverity)[keyof typeof PlanFindingSeverity]

export const PlanFindingSeverity = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
} as const
