/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PlanBuffers } from './planBuffers'
import type { PlanNodeActual } from './planNodeActual'

/**
 * One plan node. type is the canonical node name; the modifiers the text format folds into it are separate fields.
 */
export interface PlanNode {
  type: string
  relation?: string
  schema?: string
  alias?: string
  index_name?: string
  parent_relationship?: string
  subplan_name?: string
  parallel: boolean
  partial_mode?: string
  strategy?: string
  join_type?: string
  scan_direction?: string
  operation?: string
  startup_cost: number
  total_cost: number
  plan_rows: number
  plan_width: number
  actual?: PlanNodeActual
  /** at most 4 KiB, like the other conditions; *_omitted_bytes counts the rest */
  filter?: string
  /** bytes cut from the end of filter; absent when it is complete */
  filter_omitted_bytes?: number
  index_cond?: string
  index_cond_omitted_bytes?: number
  recheck_cond?: string
  recheck_cond_omitted_bytes?: number
  join_cond?: string
  join_cond_omitted_bytes?: number
  sort_key?: string[]
  rows_removed_by_filter?: number
  rows_removed_by_join_filter?: number
  heap_fetches?: number
  sort_method?: string
  sort_space_kb?: number
  sort_space_type?: string
  workers_planned?: number
  workers_launched?: number
  heap_blocks_exact?: number
  heap_blocks_lossy?: number
  buffers?: PlanBuffers
  children: PlanNode[]
}
