/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The values the wording quotes. Which keys are set depends on code; a client reads only the ones its phrasing needs.
 */
export type PlanFindingParams = { [key: string]: unknown }
