/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type PlanMissingRequirement =
  (typeof PlanMissingRequirement)[keyof typeof PlanMissingRequirement]

export const PlanMissingRequirement = {
  actual: 'actual',
  timing: 'timing',
  buffers: 'buffers',
  work_mem: 'work_mem',
} as const
