/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PlanFindingCode } from './planFindingCode'
import type { PlanFindingParams } from './planFindingParams'
import type { PlanFindingSeverity } from './planFindingSeverity'

export interface PlanFinding {
  /** Stable rule code. The wording is rendered from it and from params; the API carries no prose. */
  code: PlanFindingCode
  severity: PlanFindingSeverity
  /** child indexes from the root to the node */
  path: number[]
  node_type: string
  relation?: string
  /** The values the wording quotes. Which keys are set depends on code; a client reads only the ones its phrasing needs. */
  params?: PlanFindingParams
}
