/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface PlanTrigger {
  name: string
  relation?: string
  time_ms: number
  calls: number
}
