/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * measured per loop, as PostgreSQL prints it; the node's output is rows × loops
 */
export interface PlanNodeActual {
  startup_time_ms?: number
  total_time_ms?: number
  rows: number
  loops: number
}
