/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type PlanSummaryFormat = (typeof PlanSummaryFormat)[keyof typeof PlanSummaryFormat]

export const PlanSummaryFormat = {
  text: 'text',
  json: 'json',
} as const
