/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { PlanNotParsedCode } from './planNotParsedCode'

export interface PlanNotParsed {
  /** unsupported_plan_format - xml or yaml; empty_plan; parse_error; plan_too_large - larger than max_plan_bytes; plan_budget_exhausted - past max_plans. */
  code: PlanNotParsedCode
  count: number
}
