/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Stable rule code. The wording is rendered from it and from params; the API carries no prose.
 */
export type PlanFindingCode = (typeof PlanFindingCode)[keyof typeof PlanFindingCode]

export const PlanFindingCode = {
  seq_scan_large: 'seq_scan_large',
  cost_hotspot: 'cost_hotspot',
  nested_loop_blowup: 'nested_loop_blowup',
  index_candidate_join: 'index_candidate_join',
  sort_estimate_spill: 'sort_estimate_spill',
  cte_materialize: 'cte_materialize',
  row_misestimate: 'row_misestimate',
  sort_spill_actual: 'sort_spill_actual',
  filter_discards_rows: 'filter_discards_rows',
  heap_fetches_high: 'heap_fetches_high',
  loops_blowup: 'loops_blowup',
  bitmap_lossy: 'bitmap_lossy',
  workers_not_launched: 'workers_not_launched',
  jit_overhead: 'jit_overhead',
  trigger_time: 'trigger_time',
} as const
