/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface PlanBuffers {
  shared_hit: number
  shared_read: number
  shared_dirtied: number
  shared_written: number
  local_hit: number
  local_read: number
  local_dirtied: number
  local_written: number
  temp_read: number
  temp_written: number
}
