/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface PlanJIT {
  functions: number
  generation_ms?: number
  inlining_ms?: number
  optimization_ms?: number
  emission_ms?: number
  total_ms?: number
}
