/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ClusterNameParameter } from './clusterNameParameter'
import type { DatabaseParameter } from './databaseParameter'
import type { InstanceParameter } from './instanceParameter'

export type PostSnapshotParams = {
  cluster_name: ClusterNameParameter
  instance: InstanceParameter
  database: DatabaseParameter
  /**
   * Also capture a lock snapshot (probes blocked sessions)
   */
  include_locks?: boolean
}
