/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ProgressVacuum {
  Pid: number;
  Datname: string;
  TableName: string;
  PhaseDescription: string;
  HeapBlksTotal: number;
  HeapBlksScanned: number;
  HeapBlksVacuumed: number;
  IndexVacuumCount: number;
  MaxDeadTuples: number;
  NumDeadTuples: number;
}
