/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ProgressCluster {
  Pid: number;
  Datname: string;
  TableName: string;
  Command: string;
  PhaseDescription: string;
  ClusterIndex: string;
  HeapTuplesScanned: number;
  HeapTuplesWritten: number;
  HeapBlksTotal: number;
  HeapBlksScanned: number;
  IndexRebuildCount: number;
}
