/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ProgressAnalyze {
  Pid: number
  Datname: string
  TableName: string
  Phase: string
  SampleBlksTotal: number
  SampleBlksScanned: number
  ExtStatsTotal: number
  ExtStatsComputed: number
  CurrentChildTable: string
}
