/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ProgressBaseBackup {
  Pid: number
  Phase: string
  BackupTotal: number
  BackupStreamed: number
  /** @nullable */
  ProgressPercentage?: number | null
  TablespacesTotal: number
  TablespacesStreamed: number
}
