/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ProgressCluster {
  Pid: number
  Datname: string
  TableName: string
  Command: string
  Phase: string
  ClusterIndex: string
  HeapTuplesScanned: number
  HeapTuplesWritten: number
  HeapBlksTotal: number
  HeapBlksScanned: number
  IndexRebuildCount: number
}
