/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ProgressBaseBackup {
  Pid: number;
  PhaseDescription: string;
  BackupTotal: number;
  BackupStreamed: number;
  /** @nullable */
  ProgressPercentage?: number | null;
  TablespacesTotal: number;
  TablespacesStreamed: number;
}
