/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ProgressIndex {
  Pid: number;
  Datname: string;
  TableName: string;
  IndexName: string;
  PhaseDescription: string;
  LockersTotal: number;
  LockersDone: number;
  CurrentLockerPid: number;
  BlocksTotal: number;
  BlocksDone: number;
  TuplesTotal: number;
  TuplesDone: number;
  PartitionsTotal: number;
  PartitionsDone: number;
}
