/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ProgressVacuum {
  Pid: number
  Datname: string
  TableName: string
  Phase: string
  HeapBlksTotal: number
  HeapBlksScanned: number
  HeapBlksVacuumed: number
  IndexVacuumCount: number
  MaxDeadTuples: number
  NumDeadTuples: number
}
