/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface QueryTop10ChartItem {
  /** pg_stat_statements queryid as string to preserve int64 precision in JavaScript */
  QueryID: string
  /** Database this entry belongs to; empty when the database no longer exists. */
  Datname: string
  Pct: number
}
