/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorMessage } from './errorMessage'

/**
 * The request did not complete within its timeout — the database, or another service it queries, did not answer in time. Any endpoint may answer with it; a wait on a lock is reported as 423 instead.

 */
export type QueryTimeoutResponse = ErrorMessage
