/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryTop10ChartItem } from './queryTop10ChartItem'

export interface QueryTop10Chart {
  Calls: QueryTop10ChartItem[]
  TotalExecTime: QueryTop10ChartItem[]
  Rows: QueryTop10ChartItem[]
  SharedBlksHit: QueryTop10ChartItem[]
  SharedBlksRead: QueryTop10ChartItem[]
  SharedBlksDirtied: QueryTop10ChartItem[]
  TempBlksRead: QueryTop10ChartItem[]
  TempBlksWritten: QueryTop10ChartItem[]
  WalRecords: QueryTop10ChartItem[]
}
