/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * One aggregated pg_stat_statements entry of a single database. A queryid is only unique within a database, so a row is identified by the pair (QueryID, Datname). Percentage fields are shares within the requested scope — the database for scope=database, the whole instance otherwise.

 */
export interface QueryReport {
  /** pg_stat_statements queryid as string to preserve int64 precision in JavaScript */
  QueryID: string
  Query: string
  /** Database this entry belongs to. Empty when the database no longer exists, or when the row comes from a snapshot stored before per-database attribution existed (json_version 1).
   */
  Datname?: string
  /**
   * Distinct PostgreSQL roles that executed this queryid (aggregated across pg_stat_statements rows).
   * @nullable
   */
  Usernames?: string[] | null
  /**
   * max(stddev_exec_time) across aggregated pg_stat_statements rows, in milliseconds.
   * @nullable
   */
  StddevExecTimeMs?: number | null
  /**
   * max(stddev_plan_time) across aggregated pg_stat_statements rows, in milliseconds.
   * @nullable
   */
  StddevPlanTimeMs?: number | null
  /** @nullable */
  Rows?: number | null
  /** @nullable */
  RowsPct?: number | null
  /** @nullable */
  Calls?: number | null
  /** @nullable */
  CallsPct?: number | null
  /** @nullable */
  TotalTimeMs?: number | null
  /** @nullable */
  TotalTimePct?: number | null
  /** @nullable */
  ExecTimeMs?: number | null
  /** @nullable */
  MinExecTimeMs?: number | null
  /** @nullable */
  MaxExecTimeMs?: number | null
  /** @nullable */
  MeanExecTimeMs?: number | null
  /** @nullable */
  PlanTimeMs?: number | null
  /** @nullable */
  MinPlanTimeMs?: number | null
  /** @nullable */
  MaxPlanTimeMs?: number | null
  /** @nullable */
  MeanPlanTimeMs?: number | null
  /** @nullable */
  IoTimeMs?: number | null
  /** @nullable */
  IoTimePct?: number | null
  /** @nullable */
  CpuTimeMs?: number | null
  /** @nullable */
  CpuTimePct?: number | null
  /** @nullable */
  CacheHitRatio?: number | null
  /** @nullable */
  SharedBlksDirtiedPct?: number | null
  /** @nullable */
  SharedBlksWrittenPct?: number | null
  /** @nullable */
  WalBytes?: number | null
  /** @nullable */
  WalBytesPct?: number | null
  /** @nullable */
  WalRecords?: number | null
  /** @nullable */
  WalFpi?: number | null
  /** @nullable */
  TempBlks?: number | null
  /** @nullable */
  TempBlksPct?: number | null
}
