/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface QueryTop10ByWal {
  QueryID: number;
  WalVolume: string;
  WalBytes: number;
  QueryTrunc: string;
}
