/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface QueryBlocked {
  LockedItem: string;
  BlockedPid: number;
  BlockedUser: string;
  BlockedQuery: string;
  BlockedDuration: string;
  BlockedMode: string;
  BlockingPid: number;
  BlockingUser: string;
  StateOfBlockingProcess: string;
  CurrentOrRecentQueryInBlockingProcess: string;
  BlockingDuration: string;
  BlockingMode: string;
}
