/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryReportMetrics } from './queryReportMetrics'

export interface QueryCompareItem {
  /** pg_stat_statements queryid as string to preserve int64 precision in JavaScript */
  QueryID: string
  Query: string
  Left?: QueryReportMetrics | null
  Right?: QueryReportMetrics | null
}
