/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface QueryStatsStatus {
  Available: boolean
  Enabled: boolean
  Readable: boolean
  /** True when the connected role has no privileges of pg_read_all_stats. The statistics view then reports neither the identifier nor the text of the statements of other users, and those rows are left out of every report. */
  Restricted: boolean
  /** Query-statistics extension this connection is read through: pg_stat_statements, or pgpro_stats on Postgres Pro. Always set — when neither is installed it names the one worth installing here. */
  Source: string
}
