/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryReportMetrics } from './queryReportMetrics'

export interface QueryCompareItem {
  QueryID: number
  Query: string
  Left?: QueryReportMetrics | null
  Right?: QueryReportMetrics | null
}
