/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorMessage } from './errorMessage'

/**
 * The database did not answer within the query timeout — an overloaded instance, or a wait the lock timeout does not cover.

 */
export type QueryTimeoutResponse = ErrorMessage
