/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface QueryReport {
  QueryID: number;
  Query: string;
  /** @nullable */
  Rows?: number | null;
  /** @nullable */
  RowsPct?: number | null;
  /** @nullable */
  Calls?: number | null;
  /** @nullable */
  CallsPct?: number | null;
  /** @nullable */
  TotalTimeMs?: number | null;
  /** @nullable */
  TotalTimePct?: number | null;
  /** @nullable */
  ExecTimeMs?: number | null;
  /** @nullable */
  MinExecTimeMs?: number | null;
  /** @nullable */
  MaxExecTimeMs?: number | null;
  /** @nullable */
  MeanExecTimeMs?: number | null;
  /** @nullable */
  PlanTimeMs?: number | null;
  /** @nullable */
  MinPlanTimeMs?: number | null;
  /** @nullable */
  MaxPlanTimeMs?: number | null;
  /** @nullable */
  MeanPlanTimeMs?: number | null;
  /** @nullable */
  IoTimeMs?: number | null;
  /** @nullable */
  IoTimePct?: number | null;
  /** @nullable */
  CpuTimeMs?: number | null;
  /** @nullable */
  CpuTimePct?: number | null;
  /** @nullable */
  CacheHitRatio?: number | null;
  /** @nullable */
  SharedBlksDirtiedPct?: number | null;
  /** @nullable */
  SharedBlksWrittenPct?: number | null;
  /** @nullable */
  WalBytes?: number | null;
  /** @nullable */
  WalBytesPct?: number | null;
  /** @nullable */
  WalRecords?: number | null;
  /** @nullable */
  WalFpi?: number | null;
  /** @nullable */
  TempBlks?: number | null;
  /** @nullable */
  TempBlksPct?: number | null;
}
