/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface QueryBlocked {
  /** Relation name of the lock target, or its OID when the target lives in another database: names resolve through the catalog of the database the backend reads from.
   */
  LockedItem: string
  BlockedPid: number
  /** Database of the blocked session (the blocking one is always in the same database). */
  BlockedDatabase: string
  BlockedUser: string
  BlockedQuery: string
  BlockedDuration: string
  /** @nullable */
  BlockedDurationMs?: number | null
  BlockedMode: string
  BlockingPid: number
  BlockingUser: string
  StateOfBlockingProcess: string
  CurrentOrRecentQueryInBlockingProcess: string
  BlockingDuration: string
  /** @nullable */
  BlockingDurationMs?: number | null
  BlockingMode: string
}
