/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ReplicationStatus {
  Pid: number
  Usename?: string
  ApplicationName: string
  ClientAddr?: string
  State: string
  SentLsn?: string
  WriteLsn?: string
  FlushLsn?: string
  ReplayLsn?: string
  WriteLagSeconds?: number
  FlushLagSeconds?: number
  ReplayLagSeconds?: number
  ReplayLagBytes?: number
  SyncState: string
  SlotName?: string
}
