/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface ReplicationSlot {
  SlotName: string
  SlotType: string
  Database?: string
  Active: boolean
  WalStatus?: string
  /** @nullable */
  SafeWalSize?: number | null
  /** @nullable */
  BacklogBytes?: number | null
}
