/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type RoleChangeTriggerDirection =
  (typeof RoleChangeTriggerDirection)[keyof typeof RoleChangeTriggerDirection]

export const RoleChangeTriggerDirection = {
  master_to_replica: 'master_to_replica',
  replica_to_master: 'replica_to_master',
  both: 'both',
} as const
