/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { RoleChangeTriggerDirection } from './roleChangeTriggerDirection'

export interface RoleChangeTrigger {
  Enabled: boolean
  Direction: RoleChangeTriggerDirection
}
