/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { ToastCandidate } from './toastCandidate'

export interface RowEstimate {
  BlockSize: number
  Fillfactor: number
  ColumnsTotal: number
  ColumnsWithStats: number
  SumAvgWidth: number
  TupleHeaderSize: number
  NullBitmapSize: number
  EstimatedRowSize: number
  ToastThreshold: number
  WillToast: boolean
  PageUsable: number
  AvailableSpace: number
  RowsPerPage: number
  ReservedSpace: number
  RowsFitInReserved: number
  ToastCandidates: ToastCandidate[]
}
