/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type SchemaLintFindingLevel =
  (typeof SchemaLintFindingLevel)[keyof typeof SchemaLintFindingLevel]

export const SchemaLintFindingLevel = {
  error: 'error',
  warning: 'warning',
  notice: 'notice',
} as const
