/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type SchemaLintSkipReason = (typeof SchemaLintSkipReason)[keyof typeof SchemaLintSkipReason]

export const SchemaLintSkipReason = {
  insufficient_privileges: 'insufficient_privileges',
  unsupported_version: 'unsupported_version',
  disabled: 'disabled',
  error: 'error',
} as const
