/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaLintSkipReason } from './schemaLintSkipReason'

export interface SchemaLintSkip {
  /** The check that did not run, or partition_roots for the helper query whose absence leaves partition findings unrolled. */
  code: string
  reason: SchemaLintSkipReason
  /** Technical marker only — a SQLSTATE or "timeout". Never carries values read from the database, and never prose: the sentence a user reads is rendered by the client from code, reason and count. */
  detail?: string
  /** How many objects the check could not look at, when it can say. */
  count?: number
  /** Grant the monitoring role needs for this check, when it needs more than the basics. Set for insufficient_privileges. */
  required_privilege?: string
}
