/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaLintFindingLevel } from './schemaLintFindingLevel'
import type { SchemaLintFindingObjectType } from './schemaLintFindingObjectType'
import type { SchemaLintFindingParams } from './schemaLintFindingParams'

export interface SchemaLintFinding {
  /** Stable identifier of the check. Titles, explanations and fix instructions are rendered from it — the API carries no prose. */
  code: string
  level: SchemaLintFindingLevel
  object_type: SchemaLintFindingObjectType
  schema: string
  /** Object the finding is about. Equals schema for schema-level checks; for an attribute this is the relation, and the column is in params. */
  object: string
  params?: SchemaLintFindingParams
  /** Frontend route with more context on this object, when one exists. */
  related_route?: string
}
