/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaLintFinding } from './schemaLintFinding'
import type { SchemaLintSkip } from './schemaLintSkip'
import type { SchemaLintSummary } from './schemaLintSummary'

export interface SchemaLintReport {
  /** Page of findings, worst level first. Order is stable across requests. */
  findings: SchemaLintFinding[]
  /** Checks that produced no findings because they could not run. Shown next to the findings so an unchecked schema is never mistaken for a clean one. */
  skipped: SchemaLintSkip[]
  summary: SchemaLintSummary
  /** Findings matching the filters before the page was cut. */
  total: number
  /** A check hit its row cap and its findings are incomplete. The counts are a lower bound. */
  truncated: boolean
  /** How long the checks took. */
  duration_ms: number
}
