/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export type SchemaLintFindingObjectType =
  (typeof SchemaLintFindingObjectType)[keyof typeof SchemaLintFindingObjectType]

export const SchemaLintFindingObjectType = {
  sequence: 'sequence',
  relation: 'relation',
  schema: 'schema',
  attribute: 'attribute',
  constraint: 'constraint',
  index: 'index',
} as const
