/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Findings per level, counted over the whole result, not the page.
 */
export interface SchemaLintSummary {
  error: number
  warning: number
  notice: number
}
