/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface SchemaLintDatabaseSummary {
  database: string
  error: number
  warning: number
  notice: number
  /** Checks that did not run in this database (no privilege, unsupported version, failure). Zero findings alongside a non-zero value here is an unchecked schema, not a clean one. Checks disabled in the configuration are not counted — those are a decision, not a gap. */
  skipped: number
  /** The database could not be read at all. Its counts are zero because nothing was checked, not because it is clean. */
  failed: boolean
}
