/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The values a finding's wording quotes. Which fields are set depends on code — a client reads only the ones its phrasing for that code needs.
 */
export interface SchemaLintFindingParams {
  /** Share of the sequence range already consumed — set for sequence_exhaustion. */
  used_pct?: number
  /** Current value of the sequence. */
  last_value?: number
  /** Ceiling that actually applies. For a sequence owned by an int4 column this is 2147483647 even when the sequence itself is a bigint: the column overflows first. */
  max_value?: number
  /** table.column the sequence feeds, empty when it is standalone. */
  owned_by?: string
  /** Type of the owning column. An integer here means the fix is a column type change, not just ALTER SEQUENCE — a long operation needing a window. */
  owned_column_type?: string
  /** Schema owner — set for public_create_privilege. */
  owner?: string
  /** Column the finding is about — set when object_type is attribute. */
  column?: string
  /** Declared type of that column, e.g. character varying(36). */
  column_type?: string
  /** Constraint the finding is about — set when object_type is constraint. */
  constraint?: string
  /** schema.table on the other side of a foreign key, when the constraint is one. */
  referenced_by?: string
  /** Index the finding is about — set when object_type is index. */
  index?: string
  /** The second half of a finding stated as a pair: the similar index, the similar key, the referenced table, or the columns a key covers. */
  other_object?: string
  /** Partitions rolled up into this row. Present when the same defect was found on the partitions of one table; the finding addresses the root table. */
  partitions?: number
  /** The table's unique index covers a nullable column — set for no_primary_key. Such an index cannot serve as REPLICA IDENTITY, so "you already have a unique index" would be wrong advice. */
  unique_nullable?: boolean
}
