/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Which slice of the instance the answer covers: `database` — only the rows of the named database, `instance` — every database of the host. Defaults to `database` when a database is named and to `instance` otherwise, so callers written before this parameter keep their instance-wide answer. Percentage fields are shares within the chosen scope.

 */
export type ScopeParameter = string
