/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { SettingsNotificationParams } from './settingsNotificationParams'

export interface SettingsNotification {
  Key: string
  Params: SettingsNotificationParams
}
