/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { SettingsNotificationParams } from './settingsNotificationParams';

export interface SettingsNotification {
  Key: string;
  Params: SettingsNotificationParams;
}
