/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface SnapshotListItem {
  Id: string
  CreatedAt: string
  DashaVersion: string
  JsonVersion: number
  /** @nullable */
  PgssStatsReset?: string | null
}
