/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface SnapshotListItem {
  Id: string
  CreatedAt: string
  DashaVersion: string
  JsonVersion: number
  /** Database the snapshot was read through. Provenance only — the contents cover every database of the instance.
   */
  Database?: string
  /** Databases represented inside the snapshot; empty for json_version 1. */
  Databases?: string[]
  /** @nullable */
  PgssStatsReset?: string | null
  /** True when a lock snapshot was captured alongside this snapshot */
  HasLocks?: boolean
  /** Why the snapshot was created: "manual" or "auto:<trigger_type>" */
  Reason?: string
  /**
     * Query-statistics extension the snapshot was read through (pg_stat_statements or pgpro_stats). Null for snapshots taken before this was recorded. The two number queryid differently, so snapshots from different sources are not comparable row by row.

     * @nullable
     */
  StatsSource?: string | null
}
