/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface TablePartition {
  ParentSchema: string;
  Parent: string;
  ChildsCount: number;
  ChildsSizeBytes: number;
  ChildsSize: string;
  ChildsAvgSizeBytes: number;
  ChildsAvgSize: string;
}
