/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { TableDescribeColumn } from './tableDescribeColumn'
import type { TableDescribeConstraint } from './tableDescribeConstraint'
import type { TableDescribeIndex } from './tableDescribeIndex'
import type { TableDescribeReferencedBy } from './tableDescribeReferencedBy'

export interface TableDescribe {
  Schema: string
  TableName: string
  TableType: string
  AccessMethod: string
  Tablespace: string
  Options: string
  SizeTotal: string
  SizeTable: string
  SizeToast: string
  SizeIndexes: string
  EstimatedRows: number
  StatInfo: string
  PartitionOf: string
  Columns: TableDescribeColumn[]
  Indexes: TableDescribeIndex[]
  CheckConstraints: TableDescribeConstraint[]
  FkConstraints: TableDescribeConstraint[]
  ReferencedBy: TableDescribeReferencedBy[]
}
