/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface TableDescribeColumn {
  Name: string
  Type: string
  Collation: string
  Nullable: boolean
  Default: string
  Storage: string
  Description: string
}
