/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface TableDescribePartition {
  Schema: string
  Name: string
  PartitionExpression: string
  SizeBytes: number
  Size: string
}
