/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface TableDescribeIndex {
  Name: string
  Definition: string
  IsPrimary: boolean
  IsUnique: boolean
  IsValid: boolean
  SizeBytes: number
  Size: string
}
