/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface TableCaching {
  Schema: string
  Table: string
  /** @nullable */
  HitRate?: number | null
  /** @nullable */
  IdxHitRate?: number | null
  /** @nullable */
  ToastHitRate?: number | null
  /** @nullable */
  ToastIdxHitRate?: number | null
}
