/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface TableDescribeBloat {
  TableLen: number
  TableLenPretty: string
  ApproxTupleCount: number
  ApproxTupleLen: number
  ApproxTupleLenPretty: string
  ApproxTuplePercent: number
  DeadTupleCount: number
  DeadTupleLen: number
  DeadTupleLenPretty: string
  DeadTuplePercent: number
  ApproxFreeSpace: number
  ApproxFreeSpacePretty: string
  ApproxFreePercent: number
}
