/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface TableTopKBySize {
  Table: string
  NIdx: number
  TotalBytes: number
  Total: string
  Toast: string
  Indexes: string
  Main: string
  Fsm: string
  Vm: string
  StatInfo: string
  Bloat: string
  Options: string
}
