/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { TriggerEventTriggerContext } from './triggerEventTriggerContext'

export interface TriggerEvent {
  Id: string
  CreatedAt: string
  ClusterName: string
  Instance: string
  /** @nullable */
  Database?: string | null
  TriggerType: string
  Outcome: string
  /** @nullable */
  SnapshotId?: string | null
  TriggerContext?: TriggerEventTriggerContext
  /** @nullable */
  ErrorMessage?: string | null
}
