/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import type { TriggerEvent } from './triggerEvent'

export interface TriggerEventList {
  Items: TriggerEvent[]
  Total: number
}
