/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */

export interface VacuumStats {
  /** @nullable */
  LastVacuum?: string | null
  /** @nullable */
  LastAutovacuum?: string | null
  /** @nullable */
  LastAnalyze?: string | null
  /** @nullable */
  LastAutoanalyze?: string | null
  DeadTuples: number
  LiveTuples: number
  ModSinceAnalyze: number
  InsSinceVacuum: number
  VacuumThreshold: number
  AnalyzeThreshold: number
  InsertVacThreshold: number
}
