{{- if .Values.secrets.externalSecret.enabled }}
{{- $es := .Values.secrets.externalSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "dasha.fullname" $ }}-env
  namespace: {{ template "dasha.namespace" $ }}
  labels:
    {{- include "dasha.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    {{- toYaml $es.secretStoreRef | nindent 4 }}
  refreshInterval: {{ $es.refreshInterval }}
  target:
    name: {{ template "dasha.fullname" $ }}-env
  data:
    {{- toYaml $es.data | nindent 4 }}
{{- end }}
