package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

func main() {
	sqlRoot := "backend/internal/query/sql"

	queries := collectQueries(sqlRoot)

	generateEnumFile(queries)
}

func collectQueries(root string) []string {
	var queries []string

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if path == root {
			return nil
		}

		if !d.IsDir() && strings.HasSuffix(path, ".tmpl.sql") {
			relPath, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}

			relPath = strings.TrimSuffix(relPath, ".tmpl.sql")
			parts := strings.Split(relPath, string(os.PathSeparator))

			var queryName string
			if len(parts) == 1 {
				queryName = parts[0]
			} else if len(parts) == 2 {
				queryName = strings.Join(parts, "/")
			} else {
				queryName = parts[0] + "/" + parts[1]
			}

			queries = append(queries, queryName)
		}

		return nil
	})

	if err != nil {
		panic(err)
	}

	queries = removeDuplicates(queries)
	sort.Strings(queries)
	return queries
}

func removeDuplicates(queries []string) []string {
	seen := make(map[string]bool)
	result := []string{}

	for _, q := range queries {
		if !seen[q] {
			seen[q] = true
			result = append(result, q)
		}
	}

	return result
}

func generateEnumFile(queries []string) {
	targetFile := "backend/internal/enums/query.go"
	fset := token.NewFileSet()

	var existingQueries []string
	var packageName string

	if _, err := os.Stat(targetFile); err == nil {
		node, err := parser.ParseFile(fset, targetFile, nil, parser.ParseComments)
		if err == nil {
			packageName = node.Name.Name

			ast.Inspect(node, func(n ast.Node) bool {
				if comment, ok := n.(*ast.Comment); ok {
					if strings.Contains(comment.Text, "ENUM(") {
						lines := strings.SplitSeq(comment.Text, "\n")
						for line := range lines {
							line = strings.TrimSpace(line)
							if strings.HasPrefix(line, "//") {
								line = strings.TrimPrefix(line, "//")
								line = strings.TrimSpace(line)
								if line != "" && line != "ENUM(" && line != ")" {
									existingQueries = append(existingQueries, line)
								}
							}
						}
					}
				}
				return true
			})
		}
	} else {
		packageName = "enums"
	}

	allQueries := make(map[string]bool)
	for _, q := range existingQueries {
		allQueries[strings.TrimSpace(q)] = true
	}
	for _, q := range queries {
		allQueries[strings.TrimSpace(q)] = true
	}

	sortedQueries := make([]string, 0, len(allQueries))
	for q := range allQueries {
		sortedQueries = append(sortedQueries, q)
	}
	sort.Strings(sortedQueries)

	tmpl := `// Code generated by make generate; DO NOT EDIT.
//go:generate go-enum --names --nocase --values

package {{.PackageName}}

// ENUM(
{{- range .Queries }}
//	{{.}}
{{- end }}
//	)
type Query string
`

	t, err := template.New("enum").Parse(tmpl)
	if err != nil {
		panic(err)
	}

	file, err := os.Create(targetFile)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	data := struct {
		PackageName string
		Queries     []string
	}{
		PackageName: packageName,
		Queries:     sortedQueries,
	}

	err = t.Execute(file, data)
	if err != nil {
		panic(err)
	}

	src, err := os.ReadFile(targetFile)
	if err != nil {
		panic(err)
	}

	formatted, err := format.Source(src)
	if err != nil {
		panic(err)
	}

	err = os.WriteFile(targetFile, formatted, 0600)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Generated enum with %d queries:\n", len(sortedQueries))
	for _, q := range sortedQueries {
		fmt.Printf("  %s\n", q)
	}
}
