FROM golang:1.26-alpine
WORKDIR /app
COPY backend/go.mod backend/go.sum ./
RUN go mod download
COPY backend/ .
RUN rm /app/dasha.yaml
RUN go build -o /usr/local/bin/dasha ./cmd/main.go
EXPOSE 8000
CMD ["dasha"]
